"""
S&P 500 + Major Company Domain Mapping
Maps ticker → list of known domains for extension lookups.
"""

DOMAIN_MAP = {
    # Tech
    "AAPL": ["apple.com", "icloud.com", "store.apple.com"],
    "MSFT": ["microsoft.com", "office.com", "azure.com", "github.com", "linkedin.com"],
    "GOOGL": ["google.com", "youtube.com", "gmail.com", "android.com"],
    "AMZN": ["amazon.com", "aws.amazon.com", "primevideo.com", "wholefoods.com"],
    "META": ["facebook.com", "instagram.com", "whatsapp.com", "meta.com", "threads.net"],
    "NVDA": ["nvidia.com"],
    "TSLA": ["tesla.com"],
    "AVGO": ["broadcom.com"],
    "ORCL": ["oracle.com"],
    "CRM": ["salesforce.com"],
    "ADBE": ["adobe.com"],
    "AMD": ["amd.com"],
    "INTC": ["intel.com"],
    "CSCO": ["cisco.com"],
    "IBM": ["ibm.com"],
    "QCOM": ["qualcomm.com"],
    "INTU": ["intuit.com", "turbotax.com", "quickbooks.com"],
    "TXN": ["ti.com"],
    "NOW": ["servicenow.com"],
    "PANW": ["paloaltonetworks.com"],
    "SNOW": ["snowflake.com"],
    "PLTR": ["palantir.com"],
    "NET": ["cloudflare.com"],
    "SHOP": ["shopify.com"],
    "SQ": ["squareup.com", "block.xyz", "cashapp.com"],
    "SNAP": ["snapchat.com", "snap.com"],
    "PINS": ["pinterest.com"],
    "UBER": ["uber.com", "ubereats.com"],
    "LYFT": ["lyft.com"],
    "ABNB": ["airbnb.com"],
    "DASH": ["doordash.com"],
    "RBLX": ["roblox.com"],
    "ZM": ["zoom.us"],
    "SPOT": ["spotify.com"],
    "DBX": ["dropbox.com"],
    "HOOD": ["robinhood.com"],
    "COIN": ["coinbase.com"],
    "U": ["unity.com"],
    "PATH": ["uipath.com"],
    "DDOG": ["datadoghq.com"],
    "ZS": ["zscaler.com"],
    "CRWD": ["crowdstrike.com"],
    "OKTA": ["okta.com"],
    "MDB": ["mongodb.com"],
    "TWLO": ["twilio.com"],
    "ESTC": ["elastic.co"],
    "DUOL": ["duolingo.com"],
    "CHGG": ["chegg.com"],
    
    # Retail
    "WMT": ["walmart.com"],
    "COST": ["costco.com"],
    "HD": ["homedepot.com"],
    "LOW": ["lowes.com"],
    "TGT": ["target.com"],
    "BKNG": ["booking.com", "priceline.com", "kayak.com"],
    "NKE": ["nike.com"],
    "SBUX": ["starbucks.com"],
    "MCD": ["mcdonalds.com"],
    "CMG": ["chipotle.com"],
    "DPZ": ["dominos.com"],
    "YUM": ["yum.com", "kfc.com", "pizzahut.com", "tacobell.com"],
    "LULU": ["lululemon.com"],
    "TJX": ["tjmaxx.com", "marshalls.com"],
    "ROST": ["rossstores.com"],
    "DG": ["dollargeneral.com"],
    "DLTR": ["dollartree.com"],
    "BBY": ["bestbuy.com"],
    "ETSY": ["etsy.com"],
    "EBAY": ["ebay.com"],
    "CHWY": ["chewy.com"],
    "W": ["wayfair.com"],
    "GPS": ["gap.com", "oldnavy.com", "bananarepublic.com"],
    "ANF": ["abercrombie.com"],
    "KR": ["kroger.com"],
    
    # Finance
    "JPM": ["jpmorgan.com", "chase.com"],
    "V": ["visa.com"],
    "MA": ["mastercard.com"],
    "BAC": ["bankofamerica.com"],
    "WFC": ["wellsfargo.com"],
    "GS": ["goldmansachs.com"],
    "MS": ["morganstanley.com"],
    "AXP": ["americanexpress.com"],
    "BLK": ["blackrock.com"],
    "C": ["citigroup.com", "citi.com"],
    "SCHW": ["schwab.com"],
    "PYPL": ["paypal.com", "venmo.com"],
    "COF": ["capitalone.com"],
    "BK": ["bnymellon.com"],
    
    # Healthcare
    "UNH": ["unitedhealthgroup.com", "uhc.com"],
    "JNJ": ["jnj.com", "johnsonandjohnson.com"],
    "LLY": ["lilly.com"],
    "PFE": ["pfizer.com"],
    "ABBV": ["abbvie.com"],
    "MRK": ["merck.com"],
    "TMO": ["thermofisher.com"],
    "ABT": ["abbott.com"],
    "BMY": ["bms.com"],
    "AMGN": ["amgen.com"],
    "GILD": ["gilead.com"],
    "ISRG": ["intuitive.com"],
    "CVS": ["cvs.com", "cvshealth.com"],
    "CI": ["cigna.com"],
    "HUM": ["humana.com"],
    "MRNA": ["modernatx.com"],
    "BIIB": ["biogen.com"],
    
    # Consumer
    "PG": ["pg.com"],
    "KO": ["coca-cola.com", "cocacola.com"],
    "PEP": ["pepsi.com", "pepsico.com", "frito-lay.com", "gatorade.com"],
    "PM": ["pmi.com"],
    "MO": ["altria.com"],
    "CL": ["colgate.com", "colgatepalmolive.com"],
    "EL": ["esteelauder.com"],
    "MDLZ": ["mondelezinternational.com"],
    "KHC": ["kraftheinzcompany.com"],
    "GIS": ["generalmills.com"],
    "K": ["kellanova.com"],
    "HSY": ["thehersheycompany.com", "hersheys.com"],
    "SJM": ["jmsmucker.com"],
    "CAG": ["conagrabrands.com"],
    "CPB": ["campbellsoupcompany.com", "campbells.com"],
    "CLX": ["clorox.com"],
    "KMB": ["kimberly-clark.com"],
    "CHD": ["churchdwight.com"],
    
    # Energy
    "XOM": ["exxonmobil.com"],
    "CVX": ["chevron.com"],
    "COP": ["conocophillips.com"],
    "SLB": ["slb.com"],
    "EOG": ["eogresources.com"],
    "ENPH": ["enphase.com"],
    
    # Industrial
    "CAT": ["caterpillar.com", "cat.com"],
    "DE": ["deere.com", "johndeere.com"],
    "HON": ["honeywell.com"],
    "UPS": ["ups.com"],
    "FDX": ["fedex.com"],
    "BA": ["boeing.com"],
    "RTX": ["rtx.com", "raytheon.com"],
    "LMT": ["lockheedmartin.com"],
    "GD": ["gd.com"],
    "GE": ["ge.com"],
    "MMM": ["3m.com"],
    "EMR": ["emerson.com"],
    
    # Telecom / Media
    "DIS": ["disney.com", "disneyplus.com", "espn.com", "hulu.com"],
    "NFLX": ["netflix.com"],
    "CMCSA": ["comcast.com", "xfinity.com", "nbcuniversal.com"],
    "T": ["att.com"],
    "VZ": ["verizon.com"],
    "TMUS": ["t-mobile.com"],
    "WBD": ["wbd.com", "hbomax.com"],
    "PARA": ["paramount.com", "paramountplus.com"],
    "FOXA": ["foxnews.com", "fox.com"],
    "NYT": ["nytimes.com"],
    "EA": ["ea.com"],
    "TTWO": ["take2games.com", "rockstargames.com"],
    "ATVI": ["activision.com", "blizzard.com"],
    
    # Auto
    "F": ["ford.com"],
    "GM": ["gm.com", "chevrolet.com", "cadillac.com"],
    "TM": ["toyota.com"],
    "RIVN": ["rivian.com"],
    "LCID": ["lucidmotors.com"],
    
    # Other
    "HPQ": ["hp.com"],
    "DELL": ["dell.com"],
    "WBA": ["walgreens.com"],
    "DUK": ["duke-energy.com"],
    "NEE": ["nexteraenergy.com"],
    "SO": ["southerncompany.com"],
    "AEP": ["aep.com"],
    "D": ["dominionenergy.com"],
    "LEVI": ["levi.com", "levis.com"],
    "TPR": ["tapestry.com", "coach.com"],
    "RL": ["ralphlauren.com"],
    "HLT": ["hilton.com"],
    "MAR": ["marriott.com"],
    "H": ["hyatt.com"],
    "WDAY": ["workday.com"],
    "ZM": ["zoom.us"],
    "VEEV": ["veeva.com"],
    "TEAM": ["atlassian.com"],
    "BILL": ["bill.com"],
    "HUBS": ["hubspot.com"],
    "FSLR": ["firstsolar.com"],
    "SEDG": ["solaredge.com"],
    "YETI": ["yeti.com"],
    "BIRD": ["allbirds.com"],
    "WRBY": ["warbyparker.com"],
    "OATLY": ["oatly.com"],
    "BYND": ["beyondmeat.com"],
    "COUR": ["coursera.org"],
}
