#!/usr/bin/env python3
"""
S&P 500 + Russell 1000 additions, as (ticker, name) tuples.

Source-of-truth for SEC EDGAR, FMP, and Yahoo pipelines. Other pipelines
(Finnhub, AlphaVantage, SEC 8-K, NewsAPI, OpenCorporates, etc.) read from
data/scores/all_scores.json which is bootstrapped by SEC/FMP/Yahoo, so
expanding this list cascades through the whole pipeline.

Auto-generated from universe_tickers (SP500 ∪ RUSSELL_1000_ADDITIONS) +
SEC company_tickers.json. International tickers from get_all_tickers() are
intentionally excluded — SEC EDGAR cannot fetch foreign filers.

Regenerate with: python3 pipeline/regen_sp500_companies.py

Note: variable is still named SP500 for backward compat with importers
(sec_edgar_pipeline.py, fmp_pipeline.py, yahoo_pipeline.py).
"""

SP500 = [
    ("A", "AGILENT TECHNOLOGIES, INC."),
    ("AA", "Alcoa Corp"),
    ("AAL", "American Airlines Group Inc."),
    ("AAON", "AAON, INC."),
    ("AAPL", "Apple Inc."),
    ("ABBV", "AbbVie Inc."),
    ("ABNB", "Airbnb, Inc."),
    ("ABT", "ABBOTT LABORATORIES"),
    ("ACGL", "ARCH CAPITAL GROUP LTD."),
    ("ACI", "Albertsons Companies, Inc."),
    ("ACLS", "AXCELIS TECHNOLOGIES INC"),
    ("ACM", "AECOM"),
    ("ACN", "Accenture plc"),
    ("ADBE", "ADOBE INC."),
    ("ADC", "AGREE REALTY CORP"),
    ("ADI", "ANALOG DEVICES INC"),
    ("ADP", "AUTOMATIC DATA PROCESSING INC"),
    ("AEE", "AMEREN CORP"),
    ("AEIS", "ADVANCED ENERGY INDUSTRIES INC"),
    ("AEO", "AMERICAN EAGLE OUTFITTERS INC"),
    ("AEP", "AMERICAN ELECTRIC POWER CO INC"),
    ("AES", "AES CORP"),
    ("AFG", "AMERICAN FINANCIAL GROUP INC"),
    ("AFL", "AFLAC INC"),
    ("AFRM", "Affirm Holdings, Inc."),
    ("AGCO", "AGCO CORP /DE"),
    ("AHR", "American Healthcare REIT, Inc."),
    ("AI", "C3.ai, Inc."),
    ("AIG", "AMERICAN INTERNATIONAL GROUP, INC."),
    ("AIT", "APPLIED INDUSTRIAL TECHNOLOGIES INC"),
    ("AIZ", "ASSURANT, INC."),
    ("AJG", "Arthur J. Gallagher & Co."),
    ("ALB", "ALBEMARLE CORP"),
    ("ALGM", "ALLEGRO MICROSYSTEMS, INC."),
    ("ALK", "ALASKA AIR GROUP, INC."),
    ("ALL", "ALLSTATE CORP"),
    ("ALLE", "Allegion plc"),
    ("ALLY", "Ally Financial Inc."),
    ("ALNY", "ALNYLAM PHARMACEUTICALS, INC."),
    ("ALSN", "Allison Transmission Holdings Inc"),
    ("ALV", "AUTOLIV INC"),
    ("AM", "Antero Midstream Corp"),
    ("AMAT", "APPLIED MATERIALS INC /DE"),
    ("AMBA", "AMBARELLA INC"),
    ("AMC", "AMC ENTERTAINMENT HOLDINGS, INC."),
    ("AMCR", "Amcor plc"),
    ("AMD", "ADVANCED MICRO DEVICES INC"),
    ("AME", "AMETEK INC/"),
    ("AMG", "AFFILIATED MANAGERS GROUP, INC."),
    ("AMGN", "AMGEN INC"),
    ("AMH", "American Homes 4 Rent"),
    ("AMKR", "AMKOR TECHNOLOGY, INC."),
    ("AMP", "AMERIPRISE FINANCIAL INC"),
    ("AMT", "AMERICAN TOWER CORP /MA/"),
    ("AMZN", "AMAZON COM INC"),
    ("AN", "AUTONATION, INC."),
    ("ANET", "Arista Networks, Inc."),
    ("ANF", "ABERCROMBIE & FITCH CO /DE/"),
    ("ANSS", "ANSS"),
    ("AON", "Aon plc"),
    ("AOS", "SMITH A O CORP"),
    ("APA", "APA Corp"),
    ("APD", "Air Products & Chemicals, Inc."),
    ("APG", "APi Group Corp"),
    ("APH", "AMPHENOL CORP /DE/"),
    ("APO", "Apollo Global Management, Inc."),
    ("APP", "AppLovin Corp"),
    ("APPF", "APPFOLIO INC"),
    ("APPN", "APPIAN CORP"),
    ("AR", "ANTERO RESOURCES Corp"),
    ("ARE", "ALEXANDRIA REAL ESTATE EQUITIES, INC."),
    ("ARMK", "Aramark"),
    ("ARRY", "Array Technologies, Inc."),
    ("ARW", "ARROW ELECTRONICS, INC."),
    ("ARWR", "ARROWHEAD PHARMACEUTICALS, INC."),
    ("ASAN", "Asana, Inc."),
    ("ASB", "ASSOCIATED BANC-CORP"),
    ("ASH", "ASHLAND INC."),
    ("ASTS", "AST SpaceMobile, Inc."),
    ("ATI", "ATI INC"),
    ("ATO", "ATMOS ENERGY CORP"),
    ("ATR", "APTARGROUP, INC."),
    ("AVAV", "AeroVironment Inc"),
    ("AVB", "AVALONBAY COMMUNITIES INC"),
    ("AVGO", "Broadcom Inc."),
    ("AVNT", "AVIENT CORP"),
    ("AVT", "AVNET INC"),
    ("AVTR", "Avantor, Inc."),
    ("AWK", "American Water Works Company, Inc."),
    ("AXON", "AXON ENTERPRISE, INC."),
    ("AXP", "AMERICAN EXPRESS CO"),
    ("AXSM", "Axsome Therapeutics, Inc."),
    ("AXTA", "Axalta Coating Systems Ltd."),
    ("AYI", "ACUITY INC. (DE)"),
    ("AZEK", "AZEK"),
    ("AZO", "AUTOZONE INC"),
    ("BA", "BOEING CO"),
    ("BAC", "BANK OF AMERICA CORP /DE/"),
    ("BAH", "Booz Allen Hamilton Holding Corp"),
    ("BBBY", "NEIGHBORHOOD INTELLIGENCE, INC."),
    ("BBWI", "Bath & Body Works, Inc."),
    ("BBY", "BEST BUY CO INC"),
    ("BC", "BRUNSWICK CORP"),
    ("BCO", "BRINKS CO"),
    ("BDC", "BELDEN INC."),
    ("BDX", "BECTON DICKINSON & CO"),
    ("BE", "Bloom Energy Corp"),
    ("BEAM", "Beam Therapeutics Inc."),
    ("BEN", "FRANKLIN RESOURCES INC"),
    ("BF.B", "BROWN FORMAN CORP"),
    ("BGS", "B&G Foods, Inc."),
    ("BHF", "Brighthouse Financial, Inc."),
    ("BIIB", "BIOGEN INC."),
    ("BILL", "BILL Holdings, Inc."),
    ("BIO", "BIO-RAD LABORATORIES, INC."),
    ("BIRD", "Smartbird, Inc."),
    ("BITF", "BITF"),
    ("BJ", "BJ's Wholesale Club Holdings, Inc."),
    ("BK", "BK"),
    ("BKH", "BLACK HILLS CORP /SD/"),
    ("BKNG", "Booking Holdings Inc."),
    ("BKR", "Baker Hughes Co"),
    ("BKSY", "BlackSky Technology Inc."),
    ("BLDP", "Ballard Power Systems Inc."),
    ("BLDR", "Builders FirstSource, Inc."),
    ("BLK", "BlackRock, Inc."),
    ("BLNK", "Blink Charging Co."),
    ("BMBL", "Bumble Inc."),
    ("BMRN", "BIOMARIN PHARMACEUTICAL INC"),
    ("BMY", "BRISTOL MYERS SQUIBB CO"),
    ("BR", "BROADRIDGE FINANCIAL SOLUTIONS, INC."),
    ("BRK.B", "BERKSHIRE HATHAWAY INC"),
    ("BRKR", "BRUKER CORP"),
    ("BRO", "BROWN & BROWN, INC."),
    ("BROS", "Dutch Bros Inc."),
    ("BRX", "Brixmor Property Group Inc."),
    ("BSX", "BOSTON SCIENTIFIC CORP"),
    ("BSY", "BENTLEY SYSTEMS INC"),
    ("BTSG", "BrightSpring Health Services, Inc."),
    ("BURL", "Burlington Stores, Inc."),
    ("BWA", "BORGWARNER INC"),
    ("BWXT", "BWX Technologies, Inc."),
    ("BX", "Blackstone Inc."),
    ("BYD", "BOYD GAMING CORP"),
    ("BYND", "BEYOND MEAT, INC."),
    ("C", "CITIGROUP INC"),
    ("CACI", "CACI INTERNATIONAL INC /DE/"),
    ("CAG", "CONAGRA BRANDS INC."),
    ("CAH", "CARDINAL HEALTH INC"),
    ("CAR", "AVIS BUDGET GROUP, INC."),
    ("CARR", "CARRIER GLOBAL Corp"),
    ("CART", "Maplebear Inc."),
    ("CASY", "CASEYS GENERAL STORES INC"),
    ("CAT", "CATERPILLAR INC"),
    ("CAVA", "CAVA GROUP, INC."),
    ("CB", "Chubb Ltd"),
    ("CBRE", "CBRE GROUP, INC."),
    ("CBSH", "COMMERCE BANCSHARES INC /MO/"),
    ("CBT", "CABOT CORP"),
    ("CCK", "CROWN HOLDINGS, INC."),
    ("CDE", "Coeur Mining, Inc."),
    ("CDNS", "CADENCE DESIGN SYSTEMS INC"),
    ("CDP", "COPT DEFENSE PROPERTIES"),
    ("CE", "Celanese Corp"),
    ("CEG", "Constellation Energy Corp"),
    ("CELH", "Celsius Holdings, Inc."),
    ("CF", "CF Industries Holdings, Inc."),
    ("CFG", "CITIZENS FINANCIAL GROUP INC/RI"),
    ("CFLT", "CFLT"),
    ("CFR", "CULLEN/FROST BANKERS, INC."),
    ("CG", "Carlyle Group Inc."),
    ("CGNX", "COGNEX CORP"),
    ("CHD", "CHURCH & DWIGHT CO INC /DE/"),
    ("CHDN", "Churchill Downs Inc"),
    ("CHE", "CHEMED CORP"),
    ("CHGG", "CHEGG, INC"),
    ("CHH", "CHOICE HOTELS INTERNATIONAL INC /DE"),
    ("CHPT", "ChargePoint Holdings, Inc."),
    ("CHRD", "Chord Energy Corp"),
    ("CHRW", "C. H. ROBINSON WORLDWIDE, INC."),
    ("CHTR", "CHARTER COMMUNICATIONS, INC. /MO/"),
    ("CHWY", "Chewy, Inc."),
    ("CI", "Cigna Group"),
    ("CL", "COLGATE PALMOLIVE CO"),
    ("CLF", "CLEVELAND-CLIFFS INC."),
    ("CLH", "CLEAN HARBORS INC"),
    ("CLNE", "Clean Energy Fuels Corp."),
    ("CLSK", "CLEANSPARK, INC."),
    ("CMA", "CMA"),
    ("CMC", "COMMERCIAL METALS Co"),
    ("CMCSA", "COMCAST CORP"),
    ("CME", "CME GROUP INC."),
    ("CMG", "CHIPOTLE MEXICAN GRILL INC"),
    ("CMI", "CUMMINS INC"),
    ("CMS", "CMS ENERGY CORP"),
    ("CNC", "CENTENE CORP"),
    ("CNH", "CNH Industrial N.V."),
    ("CNK", "Cinemark Holdings, Inc."),
    ("CNM", "Core & Main, Inc."),
    ("CNO", "CNO Financial Group, Inc."),
    ("CNX", "CNX Resources Corp"),
    ("COF", "CAPITAL ONE FINANCIAL CORP"),
    ("COIN", "Coinbase Global, Inc."),
    ("COKE", "Coca-Cola Consolidated, Inc."),
    ("COLB", "COLUMBIA BANKING SYSTEM, INC."),
    ("COLM", "COLUMBIA SPORTSWEAR CO"),
    ("COP", "CONOCOPHILLIPS"),
    ("COR", "Cencora, Inc."),
    ("COST", "COSTCO WHOLESALE CORP /NEW"),
    ("COUR", "Coursera, Inc."),
    ("CPB", "CAMPBELL'S Co"),
    ("CPRI", "Capri Holdings Ltd"),
    ("CPRT", "COPART INC"),
    ("CPT", "CAMDEN PROPERTY TRUST"),
    ("CR", "Crane Co"),
    ("CRBG", "Corebridge Financial, Inc."),
    ("CRH", "CRH PUBLIC LTD CO"),
    ("CRL", "CHARLES RIVER LABORATORIES INTERNATIONAL, INC."),
    ("CRM", "Salesforce, Inc."),
    ("CRNX", "Crinetics Pharmaceuticals, Inc."),
    ("CROX", "Crocs, Inc."),
    ("CRS", "CARPENTER TECHNOLOGY CORP"),
    ("CRSP", "CRISPR Therapeutics AG"),
    ("CRUS", "CIRRUS LOGIC, INC."),
    ("CRWD", "CrowdStrike Holdings, Inc."),
    ("CSCO", "CISCO SYSTEMS, INC."),
    ("CSL", "CARLISLE COMPANIES INC"),
    ("CSX", "CSX CORP"),
    ("CTAS", "CINTAS CORP"),
    ("CTRE", "CareTrust REIT, Inc."),
    ("CTSH", "COGNIZANT TECHNOLOGY SOLUTIONS CORP"),
    ("CTVA", "Corteva, Inc."),
    ("CUBE", "CubeSmart"),
    ("CUZ", "COUSINS PROPERTIES INC"),
    ("CVLT", "COMMVAULT SYSTEMS INC"),
    ("CVS", "CVS HEALTH Corp"),
    ("CVX", "CHEVRON CORP"),
    ("CW", "CURTISS WRIGHT CORP"),
    ("CWAN", "CWAN"),
    ("CXT", "Crane NXT, Co."),
    ("CYBR", "CYBR"),
    ("CYTK", "CYTOKINETICS INC"),
    ("CZR", "Caesars Entertainment, Inc."),
    ("D", "DOMINION ENERGY, INC"),
    ("DAL", "DELTA AIR LINES, INC."),
    ("DAR", "DARLING INGREDIENTS INC."),
    ("DASH", "DoorDash, Inc."),
    ("DAWN", "DAWN"),
    ("DBX", "DROPBOX, INC."),
    ("DCI", "DONALDSON Co INC"),
    ("DD", "DuPont de Nemours, Inc."),
    ("DDOG", "Datadog, Inc."),
    ("DE", "DEERE & CO"),
    ("DECK", "DECKERS OUTDOOR CORP"),
    ("DELL", "Dell Technologies Inc."),
    ("DG", "DOLLAR GENERAL CORP"),
    ("DHI", "HORTON D R INC /DE/"),
    ("DHR", "DANAHER CORP /DE/"),
    ("DINO", "HF Sinclair Corp"),
    ("DIOD", "DIODES INC /DEL/"),
    ("DIS", "Walt Disney Co"),
    ("DKNG", "DraftKings Inc."),
    ("DKS", "DICK'S SPORTING GOODS, INC."),
    ("DLB", "Dolby Laboratories, Inc."),
    ("DLR", "DIGITAL REALTY TRUST, INC."),
    ("DLTR", "DOLLAR TREE, INC."),
    ("DOCN", "DigitalOcean Holdings, Inc."),
    ("DOCS", "Doximity, Inc."),
    ("DOCU", "DOCUSIGN, INC."),
    ("DOV", "DOVER Corp"),
    ("DOW", "DOW INC."),
    ("DPZ", "DOMINOS PIZZA INC"),
    ("DT", "Dynatrace, Inc."),
    ("DTC", "DTC"),
    ("DTE", "DTE ENERGY CO"),
    ("DTM", "DT Midstream, Inc."),
    ("DUK", "Duke Energy CORP"),
    ("DUOL", "Duolingo, Inc."),
    ("DVA", "DAVITA INC."),
    ("DVN", "DEVON ENERGY CORP/DE"),
    ("DXC", "DXC Technology Co"),
    ("DXCM", "DEXCOM INC"),
    ("DY", "DYCOM INDUSTRIES INC"),
    ("EA", "EA"),
    ("EBAY", "EBAY INC"),
    ("ECL", "ECOLAB INC."),
    ("ED", "CONSOLIDATED EDISON INC"),
    ("EDIT", "Editas Medicine, Inc."),
    ("EEFT", "EURONET WORLDWIDE, INC."),
    ("EFX", "EQUIFAX INC"),
    ("EGP", "EASTGROUP PROPERTIES INC"),
    ("EHC", "Encompass Health Corp"),
    ("ELAN", "Elanco Animal Health Inc"),
    ("ELF", "e.l.f. Beauty, Inc."),
    ("ELS", "EQUITY LIFESTYLE PROPERTIES INC"),
    ("ELV", "Elevance Health, Inc."),
    ("EMN", "EASTMAN CHEMICAL CO"),
    ("EMR", "EMERSON ELECTRIC CO"),
    ("ENPH", "Enphase Energy, Inc."),
    ("ENS", "EnerSys"),
    ("ENSG", "ENSIGN GROUP, INC"),
    ("ENTG", "ENTEGRIS INC"),
    ("EOG", "EOG RESOURCES INC"),
    ("EPR", "EPR PROPERTIES"),
    ("EQH", "Equitable Holdings, Inc."),
    ("EQIX", "EQUINIX INC"),
    ("EQR", "ERP OPERATING LTD PARTNERSHIP"),
    ("ESAB", "ESAB Corp"),
    ("ESNT", "Essent Group Ltd."),
    ("ESS", "ESSEX PROPERTY TRUST, INC."),
    ("ESTC", "Elastic N.V."),
    ("ETN", "Eaton Corp plc"),
    ("ETR", "ENTERGY CORP /DE/"),
    ("ETSY", "ETSY INC"),
    ("EVGO", "EVgo Inc."),
    ("EVR", "Evercore Inc."),
    ("EVRG", "Evergy, Inc."),
    ("EW", "Edwards Lifesciences Corp"),
    ("EWBC", "EAST WEST BANCORP INC"),
    ("EXAS", "EXAS"),
    ("EXC", "EXELON CORP"),
    ("EXEL", "EXELIXIS, INC."),
    ("EXLS", "ExlService Holdings, Inc."),
    ("EXP", "EAGLE MATERIALS INC"),
    ("EXPO", "EXPONENT INC"),
    ("F", "FORD MOTOR CO"),
    ("FAF", "First American Financial Corp"),
    ("FANG", "Diamondback Energy, Inc."),
    ("FAST", "FASTENAL CO"),
    ("FBIN", "Fortune Brands Innovations, Inc."),
    ("FCFS", "FirstCash Holdings, Inc."),
    ("FCN", "FTI CONSULTING, INC"),
    ("FCX", "FREEPORT-MCMORAN INC"),
    ("FDX", "FEDEX CORP"),
    ("FFIN", "FIRST FINANCIAL BANKSHARES INC"),
    ("FFIV", "F5, INC."),
    ("FHI", "FEDERATED HERMES, INC."),
    ("FHN", "FIRST HORIZON CORP"),
    ("FI", "FI"),
    ("FICO", "FAIR ISAAC CORP"),
    ("FIGS", "FIGS, Inc."),
    ("FIS", "Fidelity National Information Services, Inc."),
    ("FITB", "FIFTH THIRD BANCORP"),
    ("FIVE", "FIVE BELOW, INC"),
    ("FIVN", "Five9, Inc."),
    ("FLG", "FLAGSTAR BANK, NATIONAL ASSOCIATION"),
    ("FLR", "FLUOR CORP"),
    ("FLS", "FLOWSERVE CORP"),
    ("FLYW", "Flywire Corp"),
    ("FMC", "FMC CORP"),
    ("FN", "Fabrinet"),
    ("FNB", "FNB CORP/PA/"),
    ("FND", "Floor & Decor Holdings, Inc."),
    ("FNF", "Fidelity National Financial, Inc."),
    ("FOUR", "Shift4 Payments, Inc."),
    ("FOX", "Fox Corp"),
    ("FOXA", "Fox Corp"),
    ("FR", "FIRST INDUSTRIAL REALTY TRUST INC"),
    ("FRT", "FEDERAL REALTY INVESTMENT TRUST"),
    ("FSLR", "FIRST SOLAR, INC."),
    ("FSR", "FSR"),
    ("FTI", "TechnipFMC plc"),
    ("FTNT", "Fortinet, Inc."),
    ("FTV", "Fortive Corp"),
    ("G", "Genpact LTD"),
    ("GAP", "GAP INC"),
    ("GATX", "GATX CORP"),
    ("GBCI", "GLACIER BANCORP, INC."),
    ("GD", "GENERAL DYNAMICS CORP"),
    ("GE", "GENERAL ELECTRIC CO"),
    ("GEF", "GREIF, INC"),
    ("GEHC", "GE HealthCare Technologies Inc."),
    ("GEV", "GE Vernova Inc."),
    ("GGG", "GRACO INC"),
    ("GHC", "Graham Holdings Co"),
    ("GILD", "GILEAD SCIENCES, INC."),
    ("GIS", "GENERAL MILLS INC"),
    ("GL", "GLOBE LIFE INC."),
    ("GLBE", "Global-E Online Ltd."),
    ("GLPI", "Gaming & Leisure Properties, Inc."),
    ("GLT", "GLT"),
    ("GLW", "CORNING INC /NY"),
    ("GM", "General Motors Co"),
    ("GME", "GameStop Corp."),
    ("GMED", "GLOBUS MEDICAL INC"),
    ("GNRC", "GENERAC HOLDINGS INC."),
    ("GNTX", "GENTEX CORP"),
    ("GOOG", "Alphabet Inc."),
    ("GOOGL", "Alphabet Inc."),
    ("GPC", "GENUINE PARTS CO"),
    ("GPK", "GRAPHIC PACKAGING HOLDING CO"),
    ("GPN", "GLOBAL PAYMENTS INC"),
    ("GPS", "GPS"),
    ("GS", "GOLDMAN SACHS GROUP INC"),
    ("GTLB", "Gitlab Inc."),
    ("GWRE", "Guidewire Software, Inc."),
    ("GWW", "W.W. GRAINGER, INC."),
    ("GXO", "GXO Logistics, Inc."),
    ("H", "Hyatt Hotels Corp"),
    ("HAE", "HAEMONETICS CORP"),
    ("HAIN", "HAIN CELESTIAL GROUP INC"),
    ("HAL", "HALLIBURTON CO"),
    ("HALO", "HALOZYME THERAPEUTICS, INC."),
    ("HBAN", "HUNTINGTON BANCSHARES INC /MD/"),
    ("HCA", "HCA Healthcare, Inc."),
    ("HD", "HOME DEPOT, INC."),
    ("HEI", "HEICO CORP"),
    ("HES", "HES"),
    ("HGV", "Hilton Grand Vacations Inc."),
    ("HII", "HUNTINGTON INGALLS INDUSTRIES, INC."),
    ("HIMS", "Hims & Hers Health, Inc."),
    ("HL", "HECLA MINING CO/DE/"),
    ("HLI", "HOULIHAN LOKEY, INC."),
    ("HLNE", "Hamilton Lane INC"),
    ("HLT", "Hilton Worldwide Holdings Inc."),
    ("HOG", "HARLEY-DAVIDSON, INC."),
    ("HOMB", "HOME BANCSHARES INC"),
    ("HON", "HONEYWELL INTERNATIONAL INC"),
    ("HOOD", "Robinhood Markets, Inc."),
    ("HPE", "Hewlett Packard Enterprise Co"),
    ("HPQ", "HP INC"),
    ("HQY", "HEALTHEQUITY, INC."),
    ("HR", "Healthcare Realty Trust Inc"),
    ("HRB", "H&R BLOCK INC"),
    ("HRL", "HORMEL FOODS CORP /DE/"),
    ("HSIC", "HENRY SCHEIN INC"),
    ("HSY", "HERSHEY CO"),
    ("HUBB", "HUBBELL INC"),
    ("HUBS", "HUBSPOT INC"),
    ("HUT", "Hut 8 Corp."),
    ("HWC", "HANCOCK WHITNEY CORP"),
    ("HWM", "Howmet Aerospace Inc."),
    ("HXL", "HEXCEL CORP /DE/"),
    ("IAC", "IAC"),
    ("IBM", "INTERNATIONAL BUSINESS MACHINES CORP"),
    ("IBOC", "INTERNATIONAL BANCSHARES CORP"),
    ("ICE", "Intercontinental Exchange, Inc."),
    ("IDA", "IDACORP INC"),
    ("IDCC", "InterDigital, Inc."),
    ("IDXX", "IDEXX LABORATORIES INC /DE"),
    ("IESC", "IES Holdings, Inc."),
    ("IFF", "INTERNATIONAL FLAVORS & FRAGRANCES INC"),
    ("ILMN", "ILLUMINA, INC."),
    ("IMAX", "IMAX CORP"),
    ("INCY", "INCYTE CORP"),
    ("INGR", "Ingredion Inc"),
    ("INSM", "INSMED Inc"),
    ("INTC", "INTEL CORP"),
    ("INTU", "INTUIT INC."),
    ("INVH", "Invitation Homes Inc."),
    ("IONQ", "IonQ, Inc."),
    ("IONS", "IONIS PHARMACEUTICALS INC"),
    ("IOT", "Samsara Inc."),
    ("IP", "INTERNATIONAL PAPER CO /NEW/"),
    ("IPGP", "IPG PHOTONICS CORP"),
    ("IQV", "IQVIA HOLDINGS INC."),
    ("IR", "Ingersoll Rand Inc."),
    ("IRM", "IRON MOUNTAIN INC"),
    ("IRT", "INDEPENDENCE REALTY TRUST, INC."),
    ("ISRG", "INTUITIVE SURGICAL INC"),
    ("IT", "GARTNER INC"),
    ("ITT", "ITT INC."),
    ("ITW", "ILLINOIS TOOL WORKS INC"),
    ("IVZ", "Invesco Ltd."),
    ("J", "JACOBS SOLUTIONS INC."),
    ("JAZZ", "Jazz Pharmaceuticals plc"),
    ("JBHT", "HUNT J B TRANSPORT SERVICES INC"),
    ("JBLU", "JETBLUE AIRWAYS CORP"),
    ("JCI", "Johnson Controls International plc"),
    ("JEF", "Jefferies Financial Group Inc."),
    ("JLL", "JONES LANG LASALLE INC"),
    ("JNJ", "JOHNSON & JOHNSON"),
    ("JPM", "JPMORGAN CHASE & CO"),
    ("JWN", "JWN"),
    ("K", "K"),
    ("KBH", "KB HOME"),
    ("KBR", "KBR, INC."),
    ("KD", "Kyndryl Holdings, Inc."),
    ("KDP", "Keurig Dr Pepper Inc."),
    ("KEX", "KIRBY CORP"),
    ("KEY", "KEYCORP /NEW/"),
    ("KEYS", "Keysight Technologies, Inc."),
    ("KHC", "Kraft Heinz Co"),
    ("KKR", "KKR & Co. Inc."),
    ("KLAC", "KLA CORP"),
    ("KMI", "KINDER MORGAN, INC."),
    ("KNF", "Knife River Corp"),
    ("KNSL", "Kinsale Capital Group, Inc."),
    ("KNX", "Knight-Swift Transportation Holdings Inc."),
    ("KO", "COCA COLA CO"),
    ("KR", "KROGER CO"),
    ("KRC", "KILROY REALTY CORP"),
    ("KRG", "KITE REALTY GROUP TRUST"),
    ("KRYS", "Krystal Biotech, Inc."),
    ("KSS", "KOHLS Corp"),
    ("KTOS", "KRATOS DEFENSE & SECURITY SOLUTIONS, INC."),
    ("L", "LOEWS CORP"),
    ("LAD", "LITHIA MOTORS INC"),
    ("LAMR", "LAMAR ADVERTISING CO/NEW"),
    ("LC", "LC"),
    ("LCID", "Lucid Group, Inc."),
    ("LDOS", "Leidos Holdings, Inc."),
    ("LEA", "LEAR CORP"),
    ("LECO", "LINCOLN ELECTRIC HOLDINGS INC"),
    ("LEGN", "Legend Biotech Corp"),
    ("LFUS", "LITTELFUSE INC /DE"),
    ("LGF.A", "LGF.A"),
    ("LHX", "L3HARRIS TECHNOLOGIES, INC. /DE/"),
    ("LI", "Li Auto Inc."),
    ("LIN", "LINDE PLC"),
    ("LIVN", "LivaNova PLC"),
    ("LKQ", "LKQ CORP"),
    ("LLY", "ELI LILLY & Co"),
    ("LMND", "Lemonade, Inc."),
    ("LMNR", "Limoneira CO"),
    ("LMT", "LOCKHEED MARTIN CORP"),
    ("LNT", "ALLIANT ENERGY CORP"),
    ("LNTH", "Lantheus Holdings, Inc."),
    ("LOPE", "Grand Canyon Education, Inc."),
    ("LOW", "LOWES COMPANIES INC"),
    ("LPX", "LOUISIANA-PACIFIC CORP"),
    ("LRCX", "LAM RESEARCH CORP"),
    ("LSCC", "LATTICE SEMICONDUCTOR CORP"),
    ("LSTR", "LANDSTAR SYSTEM INC"),
    ("LULU", "lululemon athletica inc."),
    ("LUNR", "Intuitive Machines, Inc."),
    ("LUV", "SOUTHWEST AIRLINES CO"),
    ("LVS", "LAS VEGAS SANDS CORP"),
    ("LYV", "Live Nation Entertainment, Inc."),
    ("M", "Macy's, Inc."),
    ("MA", "Mastercard Inc"),
    ("MAA", "MID AMERICA APARTMENT COMMUNITIES INC."),
    ("MANH", "MANHATTAN ASSOCIATES INC"),
    ("MAR", "MARRIOTT INTERNATIONAL INC /MD/"),
    ("MARA", "MARA Holdings, Inc."),
    ("MARQ", "MARQ"),
    ("MAT", "MATTEL INC /DE/"),
    ("MAXN", "MAXN"),
    ("MCD", "MCDONALDS CORP"),
    ("MCHP", "MICROCHIP TECHNOLOGY INC"),
    ("MCK", "MCKESSON CORP"),
    ("MCO", "MOODYS CORP /DE/"),
    ("MDB", "MongoDB, Inc."),
    ("MDLZ", "Mondelez International, Inc."),
    ("MDT", "Medtronic plc"),
    ("MEDP", "Medpace Holdings, Inc."),
    ("MELI", "MERCADOLIBRE INC"),
    ("META", "Meta Platforms, Inc."),
    ("MGM", "MGM Resorts International"),
    ("MHK", "MOHAWK INDUSTRIES INC"),
    ("MIDD", "MIDDLEBY Corp"),
    ("MKC", "MCCORMICK & CO INC"),
    ("MKSI", "MKS INC"),
    ("MKTX", "MARKETAXESS HOLDINGS INC"),
    ("MLI", "MUELLER INDUSTRIES INC"),
    ("MMC", "MMC"),
    ("MMM", "3M CO"),
    ("MMS", "MAXIMUS, INC."),
    ("MNDY", "monday.com Ltd."),
    ("MNST", "Monster Beverage Corp"),
    ("MNTS", "Momentus Inc."),
    ("MO", "ALTRIA GROUP, INC."),
    ("MOG.A", "MOOG INC."),
    ("MOH", "MOLINA HEALTHCARE, INC."),
    ("MORN", "Morningstar, Inc."),
    ("MOS", "MOSAIC CO"),
    ("MP", "MP Materials Corp. / DE"),
    ("MPC", "Marathon Petroleum Corp"),
    ("MPW", "MPW"),
    ("MPWR", "MONOLITHIC POWER SYSTEMS, INC."),
    ("MRCY", "MERCURY SYSTEMS INC"),
    ("MRK", "Merck & Co., Inc."),
    ("MRNA", "Moderna, Inc."),
    ("MRSH", "MARSH & MCLENNAN COMPANIES, INC."),
    ("MRVL", "Marvell Technology, Inc."),
    ("MS", "MORGAN STANLEY"),
    ("MSA", "MSA Safety Inc"),
    ("MSCI", "MSCI Inc."),
    ("MSFT", "MICROSOFT CORP"),
    ("MSI", "Motorola Solutions, Inc."),
    ("MSM", "MSC INDUSTRIAL DIRECT CO INC"),
    ("MSTR", "Strategy Inc"),
    ("MTB", "M&T BANK CORP"),
    ("MTCH", "Match Group, Inc."),
    ("MTD", "METTLER TOLEDO INTERNATIONAL INC/"),
    ("MTDR", "Matador Resources Co"),
    ("MTG", "MGIC INVESTMENT CORP"),
    ("MTN", "VAIL RESORTS INC"),
    ("MTSI", "MACOM Technology Solutions Holdings, Inc."),
    ("MTZ", "MASTEC INC"),
    ("MU", "MICRON TECHNOLOGY INC"),
    ("MUR", "MURPHY OIL CORP"),
    ("MUSA", "Murphy USA Inc."),
    ("MZTI", "MARZETTI CO"),
    ("NBIX", "NEUROCRINE BIOSCIENCES INC"),
    ("NCLH", "Norwegian Cruise Line Holdings Ltd."),
    ("NDAQ", "NASDAQ, INC."),
    ("NEE", "NEXTERA ENERGY INC"),
    ("NEM", "NEWMONT Corp /DE/"),
    ("NET", "Cloudflare, Inc."),
    ("NEU", "NEWMARKET CORP"),
    ("NFG", "NATIONAL FUEL GAS CO"),
    ("NFLX", "NETFLIX INC"),
    ("NI", "NISOURCE INC."),
    ("NIO", "NIO Inc."),
    ("NJR", "NEW JERSEY RESOURCES CORP"),
    ("NKE", "NIKE, Inc."),
    ("NLY", "ANNALY CAPITAL MANAGEMENT INC"),
    ("NNN", "NNN REIT, INC."),
    ("NOC", "NORTHROP GRUMMAN CORP /DE/"),
    ("NOV", "NOV Inc."),
    ("NOVA", "NOVA"),
    ("NOVT", "NOVANTA INC"),
    ("NOW", "ServiceNow, Inc."),
    ("NSC", "NORFOLK SOUTHERN CORP"),
    ("NTAP", "NetApp, Inc."),
    ("NTLA", "Intellia Therapeutics, Inc."),
    ("NTNX", "Nutanix, Inc."),
    ("NTRS", "NORTHERN TRUST CORP"),
    ("NUE", "NUCOR CORP"),
    ("NVDA", "NVIDIA CORP"),
    ("NVST", "Envista Holdings Corp"),
    ("NVT", "nVent Electric plc"),
    ("NWE", "NorthWestern Energy Group, Inc."),
    ("NWS", "NEWS CORP"),
    ("NWSA", "NEWS CORP"),
    ("NXST", "NEXSTAR MEDIA GROUP, INC."),
    ("NXT", "Nextpower Inc."),
    ("NYT", "NEW YORK TIMES CO"),
    ("O", "REALTY INCOME CORP"),
    ("OATL", "OATL"),
    ("OATLY", "OATLY"),
    ("OC", "Owens Corning"),
    ("ODFL", "OLD DOMINION FREIGHT LINE, INC."),
    ("OGE", "OGE ENERGY CORP."),
    ("OGS", "ONE Gas, Inc."),
    ("OHI", "OMEGA HEALTHCARE INVESTORS INC"),
    ("OKE", "ONEOK INC /NEW/"),
    ("OKTA", "Okta, Inc."),
    ("OLED", "UNIVERSAL DISPLAY CORP \\PA\\"),
    ("OLLI", "Ollie's Bargain Outlet Holdings, Inc."),
    ("OLN", "OLIN Corp"),
    ("ON", "ON SEMICONDUCTOR CORP"),
    ("ONB", "OLD NATIONAL BANCORP /IN/"),
    ("ONTO", "ONTO INNOVATION INC."),
    ("OPCH", "Option Care Health, Inc."),
    ("ORA", "ORMAT TECHNOLOGIES, INC."),
    ("ORCL", "ORACLE CORP"),
    ("ORI", "OLD REPUBLIC INTERNATIONAL CORP"),
    ("ORLY", "O REILLY AUTOMOTIVE INC"),
    ("OSK", "OSHKOSH CORP"),
    ("OTIS", "Otis Worldwide Corp"),
    ("OVV", "Ovintiv Inc."),
    ("OZK", "Bank OZK"),
    ("P", "Everpure, Inc."),
    ("PAG", "PENSKE AUTOMOTIVE GROUP, INC."),
    ("PANW", "Palo Alto Networks Inc"),
    ("PARA", "Banzai International, Inc."),
    ("PATH", "UiPath, Inc."),
    ("PAYC", "Paycom Software, Inc."),
    ("PAYX", "PAYCHEX INC"),
    ("PB", "PROSPERITY BANCSHARES INC"),
    ("PBF", "PBF Energy Inc."),
    ("PCG", "PG&E Corp"),
    ("PCOR", "PROCORE TECHNOLOGIES, INC."),
    ("PCTY", "Paylocity Holding Corp"),
    ("PCVX", "Vaxcyte, Inc."),
    ("PEGA", "PEGASYSTEMS INC"),
    ("PEN", "Penumbra Inc"),
    ("PENN", "PENN Entertainment, Inc."),
    ("PEP", "PEPSICO INC"),
    ("PFE", "PFIZER INC"),
    ("PFGC", "Performance Food Group Co"),
    ("PG", "PROCTER & GAMBLE Co"),
    ("PGR", "PROGRESSIVE CORP/OH/"),
    ("PH", "Parker-Hannifin Corp"),
    ("PII", "Polaris Inc."),
    ("PINS", "PINTEREST, INC."),
    ("PK", "Park Hotels & Resorts Inc."),
    ("PKG", "PACKAGING CORP OF AMERICA"),
    ("PLD", "Prologis, Inc."),
    ("PLNT", "Planet Fitness, Inc."),
    ("PLTR", "Palantir Technologies Inc."),
    ("PLUG", "PLUG POWER INC"),
    ("PM", "Philip Morris International Inc."),
    ("PNC", "PNC FINANCIAL SERVICES GROUP, INC."),
    ("PNFP", "Pinnacle Financial Partners, Inc."),
    ("PNW", "PINNACLE WEST CAPITAL CORP"),
    ("POOL", "POOL CORP"),
    ("POR", "PORTLAND GENERAL ELECTRIC CO /OR/"),
    ("POSH", "POSH"),
    ("POST", "Post Holdings, Inc."),
    ("POWI", "POWER INTEGRATIONS INC"),
    ("PPC", "PILGRIMS PRIDE CORP"),
    ("PPG", "PPG INDUSTRIES INC"),
    ("PPL", "PPL Corp"),
    ("PR", "Permian Resources Corp"),
    ("PRI", "Primerica, Inc."),
    ("PSA", "Public Storage"),
    ("PSMT", "PRICESMART INC"),
    ("PSN", "PARSONS CORP"),
    ("PSNY", "Polestar Automotive Holding UK PLC"),
    ("PSTG", "PSTG"),
    ("PSX", "Phillips 66"),
    ("PTC", "PTC INC."),
    ("PTON", "PELOTON INTERACTIVE, INC."),
    ("PVH", "PVH CORP. /DE/"),
    ("PWR", "QUANTA SERVICES, INC."),
    ("PYPL", "PayPal Holdings, Inc."),
    ("QCOM", "QUALCOMM INC/DE"),
    ("QLYS", "QUALYS, INC."),
    ("QRVO", "Qorvo, Inc."),
    ("QS", "QuantumScape Corp"),
    ("QUBT", "Quantum Computing Inc."),
    ("R", "RYDER SYSTEM INC"),
    ("RARE", "Ultragenyx Pharmaceutical Inc."),
    ("RBA", "RB GLOBAL INC."),
    ("RBC", "RBC Bearings INC"),
    ("RBLX", "Roblox Corp"),
    ("RCL", "ROYAL CARIBBEAN CRUISES LTD"),
    ("RDW", "Redwire Corp"),
    ("REGN", "REGENERON PHARMACEUTICALS, INC."),
    ("RENT", "Rent the Runway, Inc."),
    ("REXR", "Rexford Industrial Realty, Inc."),
    ("RF", "REGIONS FINANCIAL CORP"),
    ("RGA", "REINSURANCE GROUP OF AMERICA INC"),
    ("RGEN", "REPLIGEN CORP"),
    ("RGLD", "ROYAL GOLD INC"),
    ("RGTI", "Rigetti Computing, Inc."),
    ("RH", "RH"),
    ("RHI", "ROBERT HALF INC."),
    ("RIOT", "Riot Platforms, Inc."),
    ("RIVN", "Rivian Automotive, Inc. / DE"),
    ("RJF", "RAYMOND JAMES FINANCIAL INC"),
    ("RKLB", "Rocket Lab Corp"),
    ("RL", "RALPH LAUREN CORP"),
    ("RLI", "RLI CORP"),
    ("RMBS", "RAMBUS INC"),
    ("RMD", "RESMED INC"),
    ("RNR", "RENAISSANCERE HOLDINGS LTD"),
    ("ROIV", "Roivant Sciences Ltd."),
    ("ROK", "ROCKWELL AUTOMATION, INC"),
    ("ROKU", "ROKU, INC"),
    ("ROP", "ROPER TECHNOLOGIES INC"),
    ("ROST", "ROSS STORES, INC."),
    ("RPD", "Rapid7, Inc."),
    ("RPM", "RPM INTERNATIONAL INC/DE/"),
    ("RRC", "RANGE RESOURCES CORP"),
    ("RRX", "REGAL REXNORD CORP"),
    ("RS", "RELIANCE, INC."),
    ("RSG", "REPUBLIC SERVICES, INC."),
    ("RSI", "Rush Street Interactive, Inc."),
    ("RTX", "RTX Corp"),
    ("RUN", "Sunrun Inc."),
    ("RYAN", "RYAN SPECIALTY HOLDINGS, INC."),
    ("RYN", "RAYONIER INC"),
    ("RYTM", "RHYTHM PHARMACEUTICALS, INC."),
    ("S", "SentinelOne, Inc."),
    ("SAIA", "SAIA INC"),
    ("SAIC", "Science Applications International Corp"),
    ("SAM", "BOSTON BEER CO INC"),
    ("SANM", "SANMINA CORP"),
    ("SARO", "StandardAero, Inc."),
    ("SAVE", "SAVE"),
    ("SBRA", "Sabra Health Care REIT, Inc."),
    ("SBUX", "STARBUCKS CORP"),
    ("SCHW", "SCHWAB CHARLES CORP"),
    ("SCI", "SERVICE CORP INTERNATIONAL"),
    ("SE", "Sea Ltd"),
    ("SEDG", "SOLAREDGE TECHNOLOGIES, INC."),
    ("SEE", "SEE"),
    ("SEIC", "SEI INVESTMENTS CO"),
    ("SF", "STIFEL FINANCIAL CORP"),
    ("SFIX", "Stitch Fix, Inc."),
    ("SFM", "Sprouts Farmers Market, Inc."),
    ("SGEN", "SGEN"),
    ("SGI", "SOMNIGROUP INTERNATIONAL INC."),
    ("SHAK", "Shake Shack Inc."),
    ("SHC", "Sotera Health Co"),
    ("SHOP", "SHOPIFY INC."),
    ("SHW", "SHERWIN WILLIAMS CO"),
    ("SIGI", "SELECTIVE INSURANCE GROUP INC"),
    ("SIRI", "SIRIUS XM HOLDINGS INC."),
    ("SITE", "SiteOne Landscape Supply, Inc."),
    ("SITM", "SITIME Corp"),
    ("SJM", "J M SMUCKER Co"),
    ("SLAB", "SILICON LABORATORIES INC."),
    ("SLB", "SLB LIMITED/NV"),
    ("SLGN", "SILGAN HOLDINGS INC"),
    ("SLM", "SLM Corp"),
    ("SMCI", "Super Micro Computer, Inc."),
    ("SMG", "SCOTTS MIRACLE-GRO CO"),
    ("SMPL", "Simply Good Foods Co"),
    ("SMTC", "SEMTECH CORP"),
    ("SN", "SharkNinja, Inc."),
    ("SNA", "Snap-on Inc"),
    ("SNAP", "Snap Inc"),
    ("SNDK", "Sandisk Corp"),
    ("SNOW", "Snowflake Inc."),
    ("SNPS", "SYNOPSYS INC"),
    ("SNX", "TD SYNNEX CORP"),
    ("SO", "SOUTHERN CO"),
    ("SOFI", "SoFi Technologies, Inc."),
    ("SOLS", "Solstice Advanced Materials Inc."),
    ("SOLV", "Solventum Corp"),
    ("SON", "SONOCO PRODUCTS CO"),
    ("SOUN", "SOUNDHOUND AI, INC."),
    ("SPCE", "Virgin Galactic Holdings, Inc"),
    ("SPCX", "SPACE EXPLORATION TECHNOLOGIES CORP"),
    ("SPG", "SIMON PROPERTY GROUP INC."),
    ("SPGI", "S&P Global Inc."),
    ("SPOT", "Spotify Technology S.A."),
    ("SPXC", "SPX Technologies, Inc."),
    ("SQ", "SQ"),
    ("SR", "SPIRE INC"),
    ("SRE", "SEMPRA"),
    ("SRPT", "Sarepta Therapeutics, Inc."),
    ("SSB", "SouthState Bank Corp"),
    ("SSD", "Simpson Manufacturing Co., Inc."),
    ("ST", "Sensata Technologies Holding plc"),
    ("STAG", "STAG Industrial, Inc."),
    ("STEM", "STEM, INC."),
    ("STOR", "STOR"),
    ("STRL", "STERLING INFRASTRUCTURE, INC."),
    ("STWD", "STARWOOD PROPERTY TRUST, INC."),
    ("STX", "Seagate Technology Holdings plc"),
    ("STZ", "CONSTELLATION BRANDS, INC."),
    ("SUI", "SUN COMMUNITIES INC"),
    ("SWK", "STANLEY BLACK & DECKER, INC."),
    ("SWKS", "SKYWORKS SOLUTIONS, INC."),
    ("SWX", "Southwest Gas Holdings, Inc."),
    ("SYK", "STRYKER CORP"),
    ("SYNA", "SYNAPTICS Inc"),
    ("SYY", "SYSCO CORP"),
    ("T", "AT&T INC."),
    ("TAP", "MOLSON COORS BEVERAGE CO"),
    ("TCBI", "TEXAS CAPITAL BANCSHARES INC/TX"),
    ("TDG", "TransDigm Group INC"),
    ("TDOC", "Teladoc Health, Inc."),
    ("TDY", "TELEDYNE TECHNOLOGIES INC"),
    ("TEAM", "Atlassian Corp"),
    ("TECH", "BIO-TECHNE Corp"),
    ("TEL", "TE Connectivity plc"),
    ("TENB", "Tenable Holdings, Inc."),
    ("TER", "TERADYNE, INC"),
    ("TEX", "TEREX CORP"),
    ("TFC", "TRUIST FINANCIAL CORP"),
    ("TGTX", "TG THERAPEUTICS, INC."),
    ("THC", "TENET HEALTHCARE CORP"),
    ("THG", "HANOVER INSURANCE GROUP, INC."),
    ("THO", "THOR INDUSTRIES INC"),
    ("THS", "THS"),
    ("TJX", "TJX COMPANIES INC /DE/"),
    ("TKR", "TIMKEN CO"),
    ("TLN", "Talen Energy Corp"),
    ("TMO", "THERMO FISHER SCIENTIFIC INC."),
    ("TMUS", "T-Mobile US, Inc."),
    ("TNL", "Travel & Leisure Co."),
    ("TOL", "Toll Brothers, Inc."),
    ("TOST", "Toast, Inc."),
    ("TPR", "TAPESTRY, INC."),
    ("TREX", "TREX CO INC"),
    ("TRGP", "Targa Resources Corp."),
    ("TROW", "PRICE T ROWE GROUP INC"),
    ("TRU", "TransUnion"),
    ("TRV", "TRAVELERS COMPANIES, INC."),
    ("TSCO", "TRACTOR SUPPLY CO /DE/"),
    ("TSLA", "Tesla, Inc."),
    ("TT", "Trane Technologies plc"),
    ("TTC", "TORO CO"),
    ("TTD", "Trade Desk, Inc."),
    ("TTEK", "TETRA TECH INC"),
    ("TTMI", "TTM TECHNOLOGIES INC"),
    ("TTWO", "TAKE TWO INTERACTIVE SOFTWARE INC"),
    ("TWLO", "TWILIO INC"),
    ("TXN", "TEXAS INSTRUMENTS INC"),
    ("TXNM", "TXNM ENERGY INC"),
    ("TXRH", "Texas Roadhouse, Inc."),
    ("TXT", "TEXTRON INC"),
    ("U", "Unity Software Inc."),
    ("UBER", "Uber Technologies, Inc"),
    ("UBSI", "UNITED BANKSHARES INC/WV"),
    ("UDR", "UDR, Inc."),
    ("UFPI", "UFP INDUSTRIES INC"),
    ("UGI", "UGI CORP /PA/"),
    ("UHS", "UNIVERSAL HEALTH SERVICES INC"),
    ("ULS", "UL Solutions Inc."),
    ("ULTA", "Ulta Beauty, Inc."),
    ("UMBF", "UMB FINANCIAL CORP"),
    ("UNH", "UNITEDHEALTH GROUP INC"),
    ("UNM", "Unum Group"),
    ("UNP", "UNION PACIFIC CORP"),
    ("UPS", "UNITED PARCEL SERVICE INC"),
    ("UPST", "Upstart Holdings, Inc."),
    ("URBN", "URBAN OUTFITTERS INC"),
    ("URI", "UNITED RENTALS, INC."),
    ("USB", "US BANCORP \\DE\\"),
    ("USFD", "US Foods Holding Corp."),
    ("UTHR", "UNITED THERAPEUTICS Corp"),
    ("V", "VISA INC."),
    ("VAL", "Valaris Ltd"),
    ("VC", "VISTEON CORP"),
    ("VEEV", "VEEVA SYSTEMS INC"),
    ("VERV", "VERV"),
    ("VFC", "V F CORP"),
    ("VIAV", "VIAVI SOLUTIONS INC."),
    ("VICI", "VICI PROPERTIES INC."),
    ("VICR", "VICOR CORP"),
    ("VLO", "VALERO ENERGY CORP/TX"),
    ("VLY", "VALLEY NATIONAL BANCORP"),
    ("VMC", "Vulcan Materials CO"),
    ("VMI", "VALMONT INDUSTRIES INC"),
    ("VNO", "VORNADO REALTY TRUST"),
    ("VNOM", "Viper Energy, Inc."),
    ("VNT", "Vontier Corp"),
    ("VOYA", "Voya Financial, Inc."),
    ("VRSK", "Verisk Analytics, Inc."),
    ("VRTX", "VERTEX PHARMACEUTICALS INC / MA"),
    ("VST", "Vistra Corp."),
    ("VTR", "Ventas, Inc."),
    ("VVV", "VALVOLINE INC"),
    ("VZ", "VERIZON COMMUNICATIONS INC"),
    ("W", "Wayfair Inc."),
    ("WAB", "WESTINGHOUSE AIR BRAKE TECHNOLOGIES CORP"),
    ("WAL", "WESTERN ALLIANCE BANCORPORATION"),
    ("WAT", "WATERS CORP /DE/"),
    ("WBA", "WBA"),
    ("WBD", "Warner Bros. Discovery, Inc."),
    ("WCC", "WESCO INTERNATIONAL INC"),
    ("WDAY", "Workday, Inc."),
    ("WDC", "WESTERN DIGITAL CORP"),
    ("WEC", "WEC ENERGY GROUP, INC."),
    ("WELL", "WELLTOWER INC."),
    ("WEX", "WEX Inc."),
    ("WFC", "WELLS FARGO & COMPANY/MN"),
    ("WFRD", "Weatherford International plc"),
    ("WH", "WYNDHAM HOTELS & RESORTS, INC."),
    ("WHR", "WHIRLPOOL CORP /DE/"),
    ("WING", "Wingstop Inc."),
    ("WLK", "WESTLAKE CORP"),
    ("WM", "WASTE MANAGEMENT INC"),
    ("WMB", "WILLIAMS COMPANIES, INC."),
    ("WMG", "Warner Music Group Corp."),
    ("WMK", "WEIS MARKETS INC"),
    ("WMS", "ADVANCED DRAINAGE SYSTEMS, INC."),
    ("WMT", "Walmart Inc."),
    ("WOLF", "WOLFSPEED, INC."),
    ("WPC", "W. P. Carey Inc."),
    ("WRB", "BERKLEY W R CORP"),
    ("WRBY", "Warby Parker Inc."),
    ("WSO", "WATSCO INC"),
    ("WST", "WEST PHARMACEUTICAL SERVICES INC"),
    ("WTFC", "WINTRUST FINANCIAL CORP"),
    ("WTRG", "Essential Utilities, Inc."),
    ("WTS", "WATTS WATER TECHNOLOGIES INC"),
    ("WTW", "WILLIS TOWERS WATSON PLC"),
    ("WWD", "Woodward, Inc."),
    ("WY", "WEYERHAEUSER CO"),
    ("WYNN", "WYNN RESORTS LTD"),
    ("XEL", "XCEL ENERGY INC"),
    ("XOM", "ExxonMobil Holdings Corp"),
    ("XPEV", "XPENG INC."),
    ("XPO", "XPO, Inc."),
    ("XRAY", "DENTSPLY SIRONA Inc."),
    ("XYL", "Xylem Inc."),
    ("YETI", "YETI Holdings, Inc."),
    ("YUM", "YUM BRANDS INC"),
    ("ZBRA", "ZEBRA TECHNOLOGIES CORP"),
    ("ZI", "ZI"),
    ("ZION", "ZIONS BANCORPORATION, NATIONAL ASSOCIATION /UT/"),
    ("ZM", "Zoom Communications, Inc."),
    ("ZS", "Zscaler, Inc."),
    ("ZTS", "Zoetis Inc."),
]
