#!/usr/bin/env python3
"""
S&P 500 + Russell 1000 additions, as (ticker, name) tuples.

Source-of-truth for SEC EDGAR, FMP, and Yahoo pipelines. Other pipelines
(Finnhub, AlphaVantage, SEC 8-K, NewsAPI, OpenCorporates, etc.) read from
data/scores/all_scores.json which is bootstrapped by SEC/FMP/Yahoo, so
expanding this list cascades through the whole pipeline.

Auto-generated from universe_tickers (SP500 ∪ RUSSELL_1000_ADDITIONS) +
SEC company_tickers.json. International tickers from get_all_tickers() are
intentionally excluded — SEC EDGAR cannot fetch foreign filers.

Regenerate with: python3 pipeline/regen_sp500_companies.py

Note: variable is still named SP500 for backward compat with importers
(sec_edgar_pipeline.py, fmp_pipeline.py, yahoo_pipeline.py).
"""

SP500 = [
    ("A", "AGILENT TECHNOLOGIES, INC."),
    ("AAON", "AAON, INC."),
    ("AAPL", "Apple Inc."),
    ("ABBV", "AbbVie Inc."),
    ("ABNB", "Airbnb, Inc."),
    ("ABT", "ABBOTT LABORATORIES"),
    ("ACGL", "ARCH CAPITAL GROUP LTD."),
    ("ACLS", "AXCELIS TECHNOLOGIES INC"),
    ("ACN", "Accenture plc"),
    ("ADBE", "ADOBE INC."),
    ("ADI", "ANALOG DEVICES INC"),
    ("ADP", "AUTOMATIC DATA PROCESSING INC"),
    ("AEO", "AMERICAN EAGLE OUTFITTERS INC"),
    ("AEP", "AMERICAN ELECTRIC POWER CO INC"),
    ("AES", "AES CORP"),
    ("AFL", "AFLAC INC"),
    ("AFRM", "Affirm Holdings, Inc."),
    ("AI", "C3.ai, Inc."),
    ("AIG", "AMERICAN INTERNATIONAL GROUP, INC."),
    ("AIZ", "ASSURANT, INC."),
    ("AJG", "Arthur J. Gallagher & Co."),
    ("ALGM", "ALLEGRO MICROSYSTEMS, INC."),
    ("ALK", "ALASKA AIR GROUP, INC."),
    ("ALL", "ALLSTATE CORP"),
    ("ALLE", "Allegion plc"),
    ("ALNY", "ALNYLAM PHARMACEUTICALS, INC."),
    ("AMAT", "APPLIED MATERIALS INC /DE"),
    ("AMBA", "AMBARELLA INC"),
    ("AMC", "AMC ENTERTAINMENT HOLDINGS, INC."),
    ("AMCR", "Amcor plc"),
    ("AMD", "ADVANCED MICRO DEVICES INC"),
    ("AME", "AMETEK INC/"),
    ("AMGN", "AMGEN INC"),
    ("AMP", "AMERIPRISE FINANCIAL INC"),
    ("AMT", "AMERICAN TOWER CORP /MA/"),
    ("AMZN", "AMAZON COM INC"),
    ("ANET", "Arista Networks, Inc."),
    ("ANF", "ABERCROMBIE & FITCH CO /DE/"),
    ("ANSS", "ANSS"),
    ("AON", "Aon plc"),
    ("AOS", "SMITH A O CORP"),
    ("APA", "APA Corp"),
    ("APD", "Air Products & Chemicals, Inc."),
    ("APH", "AMPHENOL CORP /DE/"),
    ("APO", "Apollo Global Management, Inc."),
    ("APP", "AppLovin Corp"),
    ("ARE", "ALEXANDRIA REAL ESTATE EQUITIES, INC."),
    ("ARRY", "Array Technologies, Inc."),
    ("ASAN", "Asana, Inc."),
    ("ASTS", "AST SpaceMobile, Inc."),
    ("AVAV", "AeroVironment Inc"),
    ("AVB", "AVALONBAY COMMUNITIES INC"),
    ("AVGO", "Broadcom Inc."),
    ("AWK", "American Water Works Company, Inc."),
    ("AXON", "AXON ENTERPRISE, INC."),
    ("AXP", "AMERICAN EXPRESS CO"),
    ("AXSM", "Axsome Therapeutics, Inc."),
    ("AZEK", "AZEK"),
    ("AZO", "AUTOZONE INC"),
    ("BA", "BOEING CO"),
    ("BAC", "BANK OF AMERICA CORP /DE/"),
    ("BBBY", "BED BATH & BEYOND, INC."),
    ("BBWI", "Bath & Body Works, Inc."),
    ("BBY", "BEST BUY CO INC"),
    ("BDX", "BECTON DICKINSON & CO"),
    ("BE", "Bloom Energy Corp"),
    ("BEAM", "Beam Therapeutics Inc."),
    ("BEN", "FRANKLIN RESOURCES INC"),
    ("BF.B", "BROWN FORMAN CORP"),
    ("BGS", "B&G Foods, Inc."),
    ("BIIB", "BIOGEN INC."),
    ("BILL", "BILL Holdings, Inc."),
    ("BIO", "BIO-RAD LABORATORIES, INC."),
    ("BIRD", "Allbirds, Inc."),
    ("BITF", "BITF"),
    ("BK", "Bank of New York Mellon Corp"),
    ("BKNG", "Booking Holdings Inc."),
    ("BKR", "Baker Hughes Co"),
    ("BKSY", "BlackSky Technology Inc."),
    ("BLDP", "Ballard Power Systems Inc."),
    ("BLDR", "Builders FirstSource, Inc."),
    ("BLK", "BlackRock, Inc."),
    ("BLNK", "Blink Charging Co."),
    ("BMRN", "BIOMARIN PHARMACEUTICAL INC"),
    ("BMY", "BRISTOL MYERS SQUIBB CO"),
    ("BR", "BROADRIDGE FINANCIAL SOLUTIONS, INC."),
    ("BRK.B", "BERKSHIRE HATHAWAY INC"),
    ("BRO", "BROWN & BROWN, INC."),
    ("BROS", "Dutch Bros Inc."),
    ("BSX", "BOSTON SCIENTIFIC CORP"),
    ("BWA", "BORGWARNER INC"),
    ("BX", "Blackstone Inc."),
    ("BYND", "BEYOND MEAT, INC."),
    ("C", "CITIGROUP INC"),
    ("CAG", "CONAGRA BRANDS INC."),
    ("CAH", "CARDINAL HEALTH INC"),
    ("CARR", "CARRIER GLOBAL Corp"),
    ("CASY", "CASEYS GENERAL STORES INC"),
    ("CAT", "CATERPILLAR INC"),
    ("CB", "Chubb Ltd"),
    ("CBRE", "CBRE GROUP, INC."),
    ("CDNS", "CADENCE DESIGN SYSTEMS INC"),
    ("CE", "Celanese Corp"),
    ("CEG", "Constellation Energy Corp"),
    ("CELH", "Celsius Holdings, Inc."),
    ("CFG", "CITIZENS FINANCIAL GROUP INC/RI"),
    ("CFLT", "CFLT"),
    ("CHD", "CHURCH & DWIGHT CO INC /DE/"),
    ("CHGG", "CHEGG, INC"),
    ("CHPT", "ChargePoint Holdings, Inc."),
    ("CHRW", "C. H. ROBINSON WORLDWIDE, INC."),
    ("CHTR", "CHARTER COMMUNICATIONS, INC. /MO/"),
    ("CHWY", "Chewy, Inc."),
    ("CI", "Cigna Group"),
    ("CL", "COLGATE PALMOLIVE CO"),
    ("CLNE", "Clean Energy Fuels Corp."),
    ("CLSK", "CLEANSPARK, INC."),
    ("CMA", "CMA"),
    ("CMCSA", "COMCAST CORP"),
    ("CME", "CME GROUP INC."),
    ("CMG", "CHIPOTLE MEXICAN GRILL INC"),
    ("CMI", "CUMMINS INC"),
    ("CNC", "CENTENE CORP"),
    ("CNK", "Cinemark Holdings, Inc."),
    ("COF", "CAPITAL ONE FINANCIAL CORP"),
    ("COIN", "Coinbase Global, Inc."),
    ("COP", "CONOCOPHILLIPS"),
    ("COR", "Cencora, Inc."),
    ("COST", "COSTCO WHOLESALE CORP /NEW"),
    ("COUR", "Coursera, Inc."),
    ("CPB", "CAMPBELL'S Co"),
    ("CPRT", "COPART INC"),
    ("CPT", "CAMDEN PROPERTY TRUST"),
    ("CRH", "CRH PUBLIC LTD CO"),
    ("CRL", "CHARLES RIVER LABORATORIES INTERNATIONAL, INC."),
    ("CRM", "Salesforce, Inc."),
    ("CRNX", "Crinetics Pharmaceuticals, Inc."),
    ("CRSP", "CRISPR Therapeutics AG"),
    ("CRUS", "CIRRUS LOGIC, INC."),
    ("CRWD", "CrowdStrike Holdings, Inc."),
    ("CSCO", "CISCO SYSTEMS, INC."),
    ("CSX", "CSX CORP"),
    ("CTAS", "CINTAS CORP"),
    ("CTSH", "COGNIZANT TECHNOLOGY SOLUTIONS CORP"),
    ("CTVA", "Corteva, Inc."),
    ("CVS", "CVS HEALTH Corp"),
    ("CVX", "CHEVRON CORP"),
    ("CWAN", "Clearwater Analytics Holdings, Inc."),
    ("CYBR", "CYBR"),
    ("CZR", "Caesars Entertainment, Inc."),
    ("D", "DOMINION ENERGY, INC"),
    ("DAL", "DELTA AIR LINES, INC."),
    ("DASH", "DoorDash, Inc."),
    ("DAWN", "Day One Biopharmaceuticals, Inc."),
    ("DBX", "DROPBOX, INC."),
    ("DD", "DuPont de Nemours, Inc."),
    ("DDOG", "Datadog, Inc."),
    ("DE", "DEERE & CO"),
    ("DECK", "DECKERS OUTDOOR CORP"),
    ("DELL", "Dell Technologies Inc."),
    ("DG", "DOLLAR GENERAL CORP"),
    ("DHI", "HORTON D R INC /DE/"),
    ("DHR", "DANAHER CORP /DE/"),
    ("DIOD", "DIODES INC /DEL/"),
    ("DIS", "Walt Disney Co"),
    ("DKNG", "DraftKings Inc."),
    ("DKS", "DICK'S SPORTING GOODS, INC."),
    ("DLR", "DIGITAL REALTY TRUST, INC."),
    ("DLTR", "DOLLAR TREE, INC."),
    ("DOCU", "DOCUSIGN, INC."),
    ("DOV", "DOVER Corp"),
    ("DOW", "DOW INC."),
    ("DTC", "DTC"),
    ("DTE", "DTE ENERGY CO"),
    ("DUK", "Duke Energy CORP"),
    ("DUOL", "Duolingo, Inc."),
    ("DVA", "DAVITA INC."),
    ("DVN", "DEVON ENERGY CORP/DE"),
    ("DXC", "DXC Technology Co"),
    ("DXCM", "DEXCOM INC"),
    ("EA", "ELECTRONIC ARTS INC."),
    ("EBAY", "EBAY INC"),
    ("ECL", "ECOLAB INC."),
    ("ED", "CONSOLIDATED EDISON INC"),
    ("EDIT", "Editas Medicine, Inc."),
    ("EFX", "EQUIFAX INC"),
    ("ELS", "EQUITY LIFESTYLE PROPERTIES INC"),
    ("ELV", "Elevance Health, Inc."),
    ("EMN", "EASTMAN CHEMICAL CO"),
    ("EMR", "EMERSON ELECTRIC CO"),
    ("ENPH", "Enphase Energy, Inc."),
    ("EOG", "EOG RESOURCES INC"),
    ("EQIX", "EQUINIX INC"),
    ("EQR", "EQUITY RESIDENTIAL"),
    ("ESS", "ESSEX PROPERTY TRUST, INC."),
    ("ESTC", "Elastic N.V."),
    ("ETN", "Eaton Corp plc"),
    ("ETR", "ENTERGY CORP /DE/"),
    ("ETSY", "ETSY INC"),
    ("EVGO", "EVgo Inc."),
    ("EVRG", "Evergy, Inc."),
    ("EW", "Edwards Lifesciences Corp"),
    ("EXAS", "EXAS"),
    ("EXC", "EXELON CORP"),
    ("F", "FORD MOTOR CO"),
    ("FANG", "Diamondback Energy, Inc."),
    ("FAST", "FASTENAL CO"),
    ("FCX", "FREEPORT-MCMORAN INC"),
    ("FDX", "FEDEX CORP"),
    ("FFIV", "F5, INC."),
    ("FI", "FI"),
    ("FICO", "FAIR ISAAC CORP"),
    ("FIGS", "FIGS, Inc."),
    ("FIS", "Fidelity National Information Services, Inc."),
    ("FITB", "FIFTH THIRD BANCORP"),
    ("FIVE", "FIVE BELOW, INC"),
    ("FIVN", "Five9, Inc."),
    ("FMC", "FMC CORP"),
    ("FOX", "Fox Corp"),
    ("FOXA", "Fox Corp"),
    ("FRT", "FEDERAL REALTY INVESTMENT TRUST"),
    ("FSLR", "FIRST SOLAR, INC."),
    ("FSR", "FSR"),
    ("FTNT", "Fortinet, Inc."),
    ("FTV", "Fortive Corp"),
    ("GD", "GENERAL DYNAMICS CORP"),
    ("GE", "GENERAL ELECTRIC CO"),
    ("GEHC", "GE HealthCare Technologies Inc."),
    ("GEV", "GE Vernova Inc."),
    ("GILD", "GILEAD SCIENCES, INC."),
    ("GIS", "GENERAL MILLS INC"),
    ("GL", "GLOBE LIFE INC."),
    ("GLT", "GLT"),
    ("GLW", "CORNING INC /NY"),
    ("GM", "General Motors Co"),
    ("GME", "GameStop Corp."),
    ("GNRC", "GENERAC HOLDINGS INC."),
    ("GOOG", "Alphabet Inc."),
    ("GOOGL", "Alphabet Inc."),
    ("GPC", "GENUINE PARTS CO"),
    ("GPN", "GLOBAL PAYMENTS INC"),
    ("GPS", "GPS"),
    ("GS", "GOLDMAN SACHS GROUP INC"),
    ("GTLB", "Gitlab Inc."),
    ("GWW", "W.W. GRAINGER, INC."),
    ("HAIN", "HAIN CELESTIAL GROUP INC"),
    ("HAL", "HALLIBURTON CO"),
    ("HALO", "HALOZYME THERAPEUTICS, INC."),
    ("HBAN", "HUNTINGTON BANCSHARES INC /MD/"),
    ("HCA", "HCA Healthcare, Inc."),
    ("HD", "HOME DEPOT, INC."),
    ("HEI", "HEICO CORP"),
    ("HES", "HES"),
    ("HII", "HUNTINGTON INGALLS INDUSTRIES, INC."),
    ("HLT", "Hilton Worldwide Holdings Inc."),
    ("HON", "HONEYWELL INTERNATIONAL INC"),
    ("HOOD", "Robinhood Markets, Inc."),
    ("HPE", "Hewlett Packard Enterprise Co"),
    ("HPQ", "HP INC"),
    ("HRL", "HORMEL FOODS CORP /DE/"),
    ("HSIC", "HENRY SCHEIN INC"),
    ("HSY", "HERSHEY CO"),
    ("HUBB", "HUBBELL INC"),
    ("HUBS", "HUBSPOT INC"),
    ("HUT", "Hut 8 Corp."),
    ("HWM", "Howmet Aerospace Inc."),
    ("IBM", "INTERNATIONAL BUSINESS MACHINES CORP"),
    ("ICE", "Intercontinental Exchange, Inc."),
    ("IDXX", "IDEXX LABORATORIES INC /DE"),
    ("IMAX", "IMAX CORP"),
    ("INCY", "INCYTE CORP"),
    ("INSM", "INSMED Inc"),
    ("INTC", "INTEL CORP"),
    ("INTU", "INTUIT INC."),
    ("INVH", "Invitation Homes Inc."),
    ("IONQ", "IonQ, Inc."),
    ("IONS", "IONIS PHARMACEUTICALS INC"),
    ("IOT", "Samsara Inc."),
    ("IP", "INTERNATIONAL PAPER CO /NEW/"),
    ("IQV", "IQVIA HOLDINGS INC."),
    ("IR", "Ingersoll Rand Inc."),
    ("IRM", "IRON MOUNTAIN INC"),
    ("ISRG", "INTUITIVE SURGICAL INC"),
    ("IT", "GARTNER INC"),
    ("ITW", "ILLINOIS TOOL WORKS INC"),
    ("IVZ", "Invesco Ltd."),
    ("J", "JACOBS SOLUTIONS INC."),
    ("JBHT", "HUNT J B TRANSPORT SERVICES INC"),
    ("JCI", "Johnson Controls International plc"),
    ("JNJ", "JOHNSON & JOHNSON"),
    ("JPM", "JPMORGAN CHASE & CO"),
    ("JWN", "JWN"),
    ("K", "K"),
    ("KDP", "Keurig Dr Pepper Inc."),
    ("KEY", "KEYCORP /NEW/"),
    ("KEYS", "Keysight Technologies, Inc."),
    ("KHC", "Kraft Heinz Co"),
    ("KKR", "KKR & Co. Inc."),
    ("KLAC", "KLA CORP"),
    ("KMI", "KINDER MORGAN, INC."),
    ("KO", "COCA COLA CO"),
    ("KR", "KROGER CO"),
    ("KSS", "KOHLS Corp"),
    ("KTOS", "KRATOS DEFENSE & SECURITY SOLUTIONS, INC."),
    ("LC", "LendingClub Corp"),
    ("LCID", "Lucid Group, Inc."),
    ("LEGN", "Legend Biotech Corp"),
    ("LGF.A", "LGF.A"),
    ("LHX", "L3HARRIS TECHNOLOGIES, INC. /DE/"),
    ("LI", "Li Auto Inc."),
    ("LIN", "LINDE PLC"),
    ("LKQ", "LKQ CORP"),
    ("LLY", "ELI LILLY & Co"),
    ("LMNR", "Limoneira CO"),
    ("LMT", "LOCKHEED MARTIN CORP"),
    ("LNT", "ALLIANT ENERGY CORP"),
    ("LOW", "LOWES COMPANIES INC"),
    ("LRCX", "LAM RESEARCH CORP"),
    ("LSCC", "LATTICE SEMICONDUCTOR CORP"),
    ("LULU", "lululemon athletica inc."),
    ("LUNR", "Intuitive Machines, Inc."),
    ("LUV", "SOUTHWEST AIRLINES CO"),
    ("LVS", "LAS VEGAS SANDS CORP"),
    ("LYV", "Live Nation Entertainment, Inc."),
    ("M", "Macy's, Inc."),
    ("MA", "Mastercard Inc"),
    ("MAA", "MID AMERICA APARTMENT COMMUNITIES INC."),
    ("MAR", "MARRIOTT INTERNATIONAL INC /MD/"),
    ("MARA", "MARA Holdings, Inc."),
    ("MARQ", "MARQ"),
    ("MAXN", "Maxeon Solar Technologies, Ltd."),
    ("MCD", "MCDONALDS CORP"),
    ("MCHP", "MICROCHIP TECHNOLOGY INC"),
    ("MCK", "MCKESSON CORP"),
    ("MCO", "MOODYS CORP /DE/"),
    ("MDB", "MongoDB, Inc."),
    ("MDLZ", "Mondelez International, Inc."),
    ("MDT", "Medtronic plc"),
    ("MELI", "MERCADOLIBRE INC"),
    ("META", "Meta Platforms, Inc."),
    ("MGM", "MGM Resorts International"),
    ("MHK", "MOHAWK INDUSTRIES INC"),
    ("MKC", "MCCORMICK & CO INC"),
    ("MKTX", "MARKETAXESS HOLDINGS INC"),
    ("MMM", "3M CO"),
    ("MNDY", "monday.com Ltd."),
    ("MNST", "Monster Beverage Corp"),
    ("MNTS", "Momentus Inc."),
    ("MO", "ALTRIA GROUP, INC."),
    ("MOS", "MOSAIC CO"),
    ("MPC", "Marathon Petroleum Corp"),
    ("MPW", "MPW"),
    ("MPWR", "MONOLITHIC POWER SYSTEMS INC"),
    ("MRCY", "MERCURY SYSTEMS INC"),
    ("MRK", "Merck & Co., Inc."),
    ("MRNA", "Moderna, Inc."),
    ("MRSH", "MARSH & MCLENNAN COMPANIES, INC."),
    ("MRVL", "Marvell Technology, Inc."),
    ("MS", "MORGAN STANLEY"),
    ("MSCI", "MSCI Inc."),
    ("MSFT", "MICROSOFT CORP"),
    ("MSI", "Motorola Solutions, Inc."),
    ("MSTR", "Strategy Inc"),
    ("MTB", "M&T BANK CORP"),
    ("MTCH", "Match Group, Inc."),
    ("MTD", "METTLER TOLEDO INTERNATIONAL INC/"),
    ("MTSI", "MACOM Technology Solutions Holdings, Inc."),
    ("MU", "MICRON TECHNOLOGY INC"),
    ("NCLH", "Norwegian Cruise Line Holdings Ltd."),
    ("NDAQ", "NASDAQ, INC."),
    ("NEE", "NEXTERA ENERGY INC"),
    ("NEM", "NEWMONT Corp /DE/"),
    ("NET", "Cloudflare, Inc."),
    ("NFLX", "NETFLIX INC"),
    ("NI", "NISOURCE INC."),
    ("NIO", "NIO Inc."),
    ("NKE", "NIKE, Inc."),
    ("NNN", "NNN REIT, INC."),
    ("NOC", "NORTHROP GRUMMAN CORP /DE/"),
    ("NOVA", "NOVA"),
    ("NOW", "ServiceNow, Inc."),
    ("NSC", "NORFOLK SOUTHERN CORP"),
    ("NTAP", "NetApp, Inc."),
    ("NTLA", "Intellia Therapeutics, Inc."),
    ("NTRS", "NORTHERN TRUST CORP"),
    ("NUE", "NUCOR CORP"),
    ("NVDA", "NVIDIA CORP"),
    ("NWS", "NEWS CORP"),
    ("NWSA", "NEWS CORP"),
    ("O", "REALTY INCOME CORP"),
    ("OATLY", "OATLY"),
    ("ODFL", "OLD DOMINION FREIGHT LINE, INC."),
    ("OHI", "OMEGA HEALTHCARE INVESTORS INC"),
    ("OKE", "ONEOK INC /NEW/"),
    ("OKTA", "Okta, Inc."),
    ("ON", "ON SEMICONDUCTOR CORP"),
    ("ORCL", "ORACLE CORP"),
    ("ORLY", "O REILLY AUTOMOTIVE INC"),
    ("OTIS", "Otis Worldwide Corp"),
    ("PANW", "Palo Alto Networks Inc"),
    ("PARA", "PARA"),
    ("PATH", "UiPath, Inc."),
    ("PAYC", "Paycom Software, Inc."),
    ("PAYX", "PAYCHEX INC"),
    ("PCG", "PG&E Corp"),
    ("PCOR", "PROCORE TECHNOLOGIES, INC."),
    ("PCVX", "Vaxcyte, Inc."),
    ("PENN", "PENN Entertainment, Inc."),
    ("PEP", "PEPSICO INC"),
    ("PFE", "PFIZER INC"),
    ("PG", "PROCTER & GAMBLE Co"),
    ("PGR", "PROGRESSIVE CORP/OH/"),
    ("PH", "Parker-Hannifin Corp"),
    ("PINS", "PINTEREST, INC."),
    ("PKG", "PACKAGING CORP OF AMERICA"),
    ("PLD", "Prologis, Inc."),
    ("PLTR", "Palantir Technologies Inc."),
    ("PLUG", "PLUG POWER INC"),
    ("PM", "Philip Morris International Inc."),
    ("PNC", "PNC FINANCIAL SERVICES GROUP, INC."),
    ("PNW", "PINNACLE WEST CAPITAL CORP"),
    ("POOL", "POOL CORP"),
    ("POSH", "POSH"),
    ("POST", "Post Holdings, Inc."),
    ("POWI", "POWER INTEGRATIONS INC"),
    ("PPG", "PPG INDUSTRIES INC"),
    ("PPL", "PPL Corp"),
    ("PSA", "Public Storage"),
    ("PSNY", "Polestar Automotive Holding UK PLC"),
    ("PSX", "Phillips 66"),
    ("PTC", "PTC INC."),
    ("PWR", "QUANTA SERVICES, INC."),
    ("PYPL", "PayPal Holdings, Inc."),
    ("QCOM", "QUALCOMM INC/DE"),
    ("QLYS", "QUALYS, INC."),
    ("QRVO", "Qorvo, Inc."),
    ("QS", "QuantumScape Corp"),
    ("QUBT", "Quantum Computing Inc."),
    ("RARE", "Ultragenyx Pharmaceutical Inc."),
    ("RBLX", "Roblox Corp"),
    ("RCL", "ROYAL CARIBBEAN CRUISES LTD"),
    ("RDW", "Redwire Corp"),
    ("REGN", "REGENERON PHARMACEUTICALS, INC."),
    ("RENT", "Rent the Runway, Inc."),
    ("RF", "REGIONS FINANCIAL CORP"),
    ("RGTI", "Rigetti Computing, Inc."),
    ("RHI", "ROBERT HALF INC."),
    ("RIOT", "Riot Platforms, Inc."),
    ("RIVN", "Rivian Automotive, Inc. / DE"),
    ("RJF", "RAYMOND JAMES FINANCIAL INC"),
    ("RKLB", "Rocket Lab Corp"),
    ("RL", "RALPH LAUREN CORP"),
    ("RMBS", "RAMBUS INC"),
    ("RMD", "RESMED INC"),
    ("ROK", "ROCKWELL AUTOMATION, INC"),
    ("ROKU", "ROKU, INC"),
    ("ROP", "ROPER TECHNOLOGIES INC"),
    ("ROST", "ROSS STORES, INC."),
    ("RPD", "Rapid7, Inc."),
    ("RSG", "REPUBLIC SERVICES, INC."),
    ("RSI", "Rush Street Interactive, Inc."),
    ("RTX", "RTX Corp"),
    ("RUN", "Sunrun Inc."),
    ("RYTM", "RHYTHM PHARMACEUTICALS, INC."),
    ("S", "SentinelOne, Inc."),
    ("SAM", "BOSTON BEER CO INC"),
    ("SBUX", "STARBUCKS CORP"),
    ("SCHW", "SCHWAB CHARLES CORP"),
    ("SE", "Sea Ltd"),
    ("SEDG", "SOLAREDGE TECHNOLOGIES, INC."),
    ("SEE", "SEE"),
    ("SFIX", "Stitch Fix, Inc."),
    ("SFM", "Sprouts Farmers Market, Inc."),
    ("SGEN", "SGEN"),
    ("SHOP", "SHOPIFY INC."),
    ("SHW", "SHERWIN WILLIAMS CO"),
    ("SITE", "SiteOne Landscape Supply, Inc."),
    ("SITM", "SITIME Corp"),
    ("SJM", "J M SMUCKER Co"),
    ("SLAB", "SILICON LABORATORIES INC."),
    ("SLB", "SLB LIMITED/NV"),
    ("SMCI", "Super Micro Computer, Inc."),
    ("SMPL", "Simply Good Foods Co"),
    ("SNA", "Snap-on Inc"),
    ("SNAP", "Snap Inc"),
    ("SNDK", "Sandisk Corp"),
    ("SNPS", "SYNOPSYS INC"),
    ("SO", "SOUTHERN CO"),
    ("SOFI", "SoFi Technologies, Inc."),
    ("SOLV", "Solventum Corp"),
    ("SOUN", "SOUNDHOUND AI, INC."),
    ("SPCE", "Virgin Galactic Holdings, Inc"),
    ("SPG", "SIMON PROPERTY GROUP INC."),
    ("SPGI", "S&P Global Inc."),
    ("SPOT", "Spotify Technology S.A."),
    ("SQ", "SQ"),
    ("SRE", "SEMPRA"),
    ("SRPT", "Sarepta Therapeutics, Inc."),
    ("STAG", "STAG Industrial, Inc."),
    ("STEM", "STEM, INC."),
    ("STOR", "STOR"),
    ("STX", "Seagate Technology Holdings plc"),
    ("STZ", "CONSTELLATION BRANDS, INC."),
    ("SUI", "SUN COMMUNITIES INC"),
    ("SWK", "STANLEY BLACK & DECKER, INC."),
    ("SWKS", "SKYWORKS SOLUTIONS, INC."),
    ("SYK", "STRYKER CORP"),
    ("SYY", "SYSCO CORP"),
    ("T", "AT&T INC."),
    ("TAP", "MOLSON COORS BEVERAGE CO"),
    ("TDG", "TransDigm Group INC"),
    ("TDY", "TELEDYNE TECHNOLOGIES INC"),
    ("TEAM", "Atlassian Corp"),
    ("TECH", "BIO-TECHNE Corp"),
    ("TEL", "TE Connectivity plc"),
    ("TENB", "Tenable Holdings, Inc."),
    ("TER", "TERADYNE, INC"),
    ("TFC", "TRUIST FINANCIAL CORP"),
    ("TGTX", "TG THERAPEUTICS, INC."),
    ("THS", "THS"),
    ("TJX", "TJX COMPANIES INC /DE/"),
    ("TMO", "THERMO FISHER SCIENTIFIC INC."),
    ("TMUS", "T-Mobile US, Inc."),
    ("TOST", "Toast, Inc."),
    ("TPR", "TAPESTRY, INC."),
    ("TREX", "TREX CO INC"),
    ("TRGP", "Targa Resources Corp."),
    ("TROW", "PRICE T ROWE GROUP INC"),
    ("TRV", "TRAVELERS COMPANIES, INC."),
    ("TSCO", "TRACTOR SUPPLY CO /DE/"),
    ("TSLA", "Tesla, Inc."),
    ("TT", "Trane Technologies plc"),
    ("TTC", "TORO CO"),
    ("TTD", "Trade Desk, Inc."),
    ("TTWO", "TAKE TWO INTERACTIVE SOFTWARE INC"),
    ("TWLO", "TWILIO INC"),
    ("TXN", "TEXAS INSTRUMENTS INC"),
    ("TXT", "TEXTRON INC"),
    ("U", "Unity Software Inc."),
    ("UBER", "Uber Technologies, Inc"),
    ("UDR", "UDR, Inc."),
    ("UNH", "UNITEDHEALTH GROUP INC"),
    ("UNP", "UNION PACIFIC CORP"),
    ("UPS", "UNITED PARCEL SERVICE INC"),
    ("UPST", "Upstart Holdings, Inc."),
    ("URBN", "URBAN OUTFITTERS INC"),
    ("URI", "UNITED RENTALS, INC."),
    ("USB", "US BANCORP DE"),
    ("V", "VISA INC."),
    ("VEEV", "VEEVA SYSTEMS INC"),
    ("VERV", "VERV"),
    ("VICI", "VICI PROPERTIES INC."),
    ("VLO", "VALERO ENERGY CORP/TX"),
    ("VRSK", "Verisk Analytics, Inc."),
    ("VRTX", "VERTEX PHARMACEUTICALS INC / MA"),
    ("VST", "Vistra Corp."),
    ("VTR", "Ventas, Inc."),
    ("VZ", "VERIZON COMMUNICATIONS INC"),
    ("W", "Wayfair Inc."),
    ("WAB", "WESTINGHOUSE AIR BRAKE TECHNOLOGIES CORP"),
    ("WAT", "WATERS CORP /DE/"),
    ("WBA", "WBA"),
    ("WBD", "Warner Bros. Discovery, Inc."),
    ("WDAY", "Workday, Inc."),
    ("WDC", "WESTERN DIGITAL CORP"),
    ("WEC", "WEC ENERGY GROUP, INC."),
    ("WELL", "WELLTOWER INC."),
    ("WFC", "WELLS FARGO & COMPANY/MN"),
    ("WM", "WASTE MANAGEMENT INC"),
    ("WMB", "WILLIAMS COMPANIES, INC."),
    ("WMK", "WEIS MARKETS INC"),
    ("WMT", "Walmart Inc."),
    ("WOLF", "WOLFSPEED, INC."),
    ("WRBY", "Warby Parker Inc."),
    ("WST", "WEST PHARMACEUTICAL SERVICES INC"),
    ("WTW", "WILLIS TOWERS WATSON PLC"),
    ("WY", "WEYERHAEUSER CO"),
    ("WYNN", "WYNN RESORTS LTD"),
    ("XEL", "XCEL ENERGY INC"),
    ("XOM", "EXXON MOBIL CORP"),
    ("XPEV", "XPENG INC."),
    ("XRAY", "DENTSPLY SIRONA Inc."),
    ("YETI", "YETI Holdings, Inc."),
    ("YUM", "YUM BRANDS INC"),
    ("ZBRA", "ZEBRA TECHNOLOGIES CORP"),
    ("ZI", "ZI"),
    ("ZM", "Zoom Communications, Inc."),
    ("ZS", "Zscaler, Inc."),
    ("ZTS", "Zoetis Inc."),
]
