/**
 * HUMAN Score Seed Database v0.2.0
 * 200 companies across 120 categories
 * 
 * All scores are ESTIMATED based on publicly available information.
 * NO AI WAS USED TO GENERATE THESE SCORES.
 * 
 * Methodology: HUMAN Framework v1.0
 * Governed by: The HI Balance
 */

const SEED_COMPANIES = [
{
  "name": "Apple Inc.",
  "h": 52,
  "u": 45,
  "m": 38,
  "a": 55,
  "n": 42,
  "tags": ["technology", "hardware", "software"],
  "notes": "High craft in hardware design (H), but aggressive AI adoption in services. Right-to-repair improvements after years of resistance. Industry-leading renewable energy and privacy stance (A, N). Supply chain labor concerns in China (Foxconn, Pegatron) weaken M. Low algorithmic harm \u2014 no engagement-driven feed algorithms.",
  "algorithmic_harm_score": 18,
  "subsidiaries": ["Beats Electronics", "Shazam", "Claris"],
  "primary_contractors": ["Foxconn (manufacturing)", "Pegatron (assembly)", "TSMC (chips)"]
},
{
  "name": "Alphabet / Google",
  "h": 35,
  "u": 30,
  "m": 28,
  "a": 45,
  "n": 32,
  "tags": ["technology", "software", "advertising"],
  "notes": "YouTube recommendation engine linked to radicalization pipelines and children's content concerns. Search ad model incentivizes engagement over accuracy. Strong AI research but displacing human decision-making at scale. DeepMind pursuing AGI with limited public safety governance. 12,000+ layoffs (2023) while increasing AI capex. Waymo represents augmentation \u2014 but core ad business is optimization-at-all-costs. CDP disclosure strong (A).",
  "algorithmic_harm_score": 52,
  "subsidiaries": ["YouTube", "DeepMind", "Waymo", "Verily", "Google Cloud", "Waze", "Fitbit"],
  "primary_contractors": ["Cognizant (content moderation)", "Accenture (ad review)"]
},
{
  "name": "Microsoft",
  "h": 42,
  "u": 40,
  "m": 32,
  "a": 48,
  "n": 35,
  "tags": ["technology", "software", "cloud"],
  "notes": "Copilot branding across all products positions AI as augmentation \u2014 but 10,000+ layoffs concurrent with $13B OpenAI investment contradicts narrative. LinkedIn algorithm increasingly engagement-driven. GitHub Copilot raises open-source attribution ethics questions. Strong enterprise human accountability chains. Activision acquisition brings loot box / microtransaction concerns (M). Climate pledges strong but data center water usage growing (A).",
  "algorithmic_harm_score": 22,
  "subsidiaries": ["LinkedIn", "GitHub", "Activision Blizzard", "Nuance Communications", "Minecraft (Mojang)"],
  "primary_contractors": ["Accenture (cloud services)", "Infosys (support)"]
},
{
  "name": "Amazon",
  "h": 28,
  "u": 22,
  "m": 25,
  "a": 32,
  "n": 20,
  "tags": ["technology", "retail", "cloud"],
  "notes": "Dark patterns in Prime cancellation (documented by FTC). Warehouse worker conditions and surveillance algorithms under regulatory scrutiny. Alexa data collection concerns. Ring doorbell policing partnerships raise civil liberties issues. DSP contractor structure distances Amazon from delivery worker conditions. AWS dominance creates infrastructure dependency. Whole Foods acquisition maintained some human-centric operations. Mechanical Turk treats human intelligence as commodity.",
  "algorithmic_harm_score": 45,
  "subsidiaries": ["AWS", "Whole Foods", "Ring", "Twitch", "MGM", "One Medical", "Kuiper"],
  "primary_contractors": ["Delivery Service Partners (DSPs)", "Flex drivers", "Mechanical Turk workers"]
},
{
  "name": "Meta Platforms",
  "h": 30,
  "u": 20,
  "m": 18,
  "a": 38,
  "n": 22,
  "tags": ["technology", "social media", "advertising"],
  "notes": "Content moderation outsourced to contractors with documented PTSD and poor working conditions. Instagram internal research (leaked 2021) showed platform worsens teen body image and mental health. Engagement algorithms amplify outrage, misinformation, and polarization \u2014 repeatedly documented by whistleblowers. 21,000+ layoffs (2022-2023) while investing $15B+ in Reality Labs. Customer support fully automated. WhatsApp end-to-end encryption is a positive transparency signal, but parent company data practices undermine trust.",
  "algorithmic_harm_score": 72,
  "subsidiaries": ["Instagram", "WhatsApp", "Reality Labs", "Threads"],
  "primary_contractors": ["Accenture (content moderation)", "Cognizant (content moderation)", "Sama (AI training data)"]
},
{
  "name": "NVIDIA",
  "h": 55,
  "u": 52,
  "m": 52,
  "a": 42,
  "n": 48,
  "tags": ["technology", "hardware", "semiconductors"],
  "notes": "Dominant AI chip supplier \u2014 enables AI displacement across all industries but doesn't directly operate displacement algorithms. High craft in chip design (H). Strong employee satisfaction. Environmental cost from manufacturing and customer data center energy use partially attributed (A). Low direct algorithmic harm \u2014 hardware company, not platform.",
  "algorithmic_harm_score": 8,
  "subsidiaries": ["Mellanox Technologies", "Arm (attempted, failed)"]
},
{
  "name": "Tesla",
  "h": 42,
  "u": 28,
  "m": 30,
  "a": 62,
  "n": 25,
  "tags": ["automotive", "technology", "energy"],
  "notes": "Autopilot/FSD safety record under NHTSA investigation. CEO social media behavior impacts M dimension. Factory worker safety incidents documented by OSHA. Strong renewable energy mission (A) offset by lithium mining supply chain. Optimus robot program explicitly designed to replace human labor. High automation in manufacturing reduces H. Direct sales model maintains some human touchpoints.",
  "algorithmic_harm_score": 28,
  "subsidiaries": ["Tesla Energy", "Tesla Insurance", "SolarCity"]
},
{
  "name": "Netflix",
  "h": 48,
  "u": 35,
  "m": 42,
  "a": 40,
  "n": 35,
  "tags": ["technology", "entertainment", "streaming"],
  "notes": "Recommendation algorithm drives binge behavior \u2014 autoplay, skip intro, continuous viewing designed to maximize watch time. Content algorithm increasingly shapes what gets produced (creative agency concern). Low workforce \u2014 high revenue per employee ratio suggests heavy automation. Strong creative investment in human storytelling offset by algorithmic content selection. No ad-driven engagement \u2014 subscription model is cleaner than ad-supported platforms.",
  "algorithmic_harm_score": 32
},
{
  "name": "Oracle",
  "h": 42,
  "u": 35,
  "m": 30,
  "a": 42,
  "n": 32,
  "tags": ["technology", "software", "cloud"],
  "notes": "Enterprise software \u2014 low direct consumer algorithmic harm. Cerner acquisition positions Oracle in healthcare data with significant privacy implications. Aggressive cloud migration displacing on-premise IT workers. CEO compensation among highest in industry (M). Low transparency on AI integration in enterprise products.",
  "algorithmic_harm_score": 12,
  "subsidiaries": ["Cerner (healthcare IT)", "NetSuite"]
},
{
  "name": "IBM",
  "h": 48,
  "u": 38,
  "m": 42,
  "a": 45,
  "n": 42,
  "tags": ["technology", "software", "consulting"],
  "notes": "WatsonX positioned as augmentation platform \u2014 'AI for business, not replacing business.' Publicly stated AI ethics principles. But quietly discontinued Watson Health after overpromising. Red Hat acquisition maintained open-source ethos. Historical workforce reductions masked as 'rebalancing.' Pioneer in AI ethics research but commercialization sometimes contradicts principles. Weather Company data collection raises privacy questions.",
  "algorithmic_harm_score": 15,
  "subsidiaries": ["Red Hat", "The Weather Company"]
},
{
  "name": "Intel",
  "h": 52,
  "u": 48,
  "m": 45,
  "a": 40,
  "n": 45,
  "tags": ["technology", "semiconductors"],
  "notes": "Deep engineering craft in chip design. US manufacturing investment. Significant water and energy usage.",
  "algorithmic_harm_score": 5
},
{
  "name": "Samsung Electronics",
  "h": 48,
  "u": 40,
  "m": 35,
  "a": 38,
  "n": 35,
  "tags": ["technology", "hardware", "semiconductors"],
  "notes": "Large manufacturing workforce. Mix of automation and skilled labor. Supply chain labor concerns.",
  "algorithmic_harm_score": 12
},
{
  "name": "Salesforce",
  "h": 42,
  "u": 52,
  "m": 45,
  "a": 48,
  "n": 48,
  "tags": ["technology", "software", "cloud"],
  "notes": "Agentforce/Einstein AI positioned as human augmentation \u2014 copilot model. Public pledge that AI won't replace Salesforce employees (unverified long-term). Strong philanthropic model (1-1-1). But 8,000+ layoffs (2023) while launching AI products contradicts augmentation narrative. Slack acquisition maintained independent culture initially but integration increasing. High employee satisfaction historically but declining post-layoffs.",
  "algorithmic_harm_score": 14,
  "subsidiaries": ["Slack", "Tableau", "MuleSoft", "Heroku"]
},
{
  "name": "Adobe",
  "h": 48,
  "u": 42,
  "m": 40,
  "a": 48,
  "n": 38,
  "tags": ["technology", "software", "creative"],
  "notes": "Firefly AI trained on licensed/owned content \u2014 ethical AI training model compared to competitors. Creative tools augment human creators rather than replacing them. But subscription pricing and dark pattern cancellation flows documented. Figma acquisition blocked by regulators (competition concerns). Strong creative community through Behance. Stock photo business threatened by own AI tools \u2014 tension between creator ecosystem and AI efficiency.",
  "algorithmic_harm_score": 10,
  "subsidiaries": ["Figma (attempted, blocked)", "Frame.io", "Behance"]
},
{
  "name": "Spotify",
  "h": 35,
  "u": 32,
  "m": 30,
  "a": 38,
  "n": 35,
  "tags": ["technology", "music", "streaming"],
  "notes": "Recommendation algorithm drives discovery but also creates filter bubbles. Playlist algorithm increasingly determines which artists get heard \u2014 shifts power from human curators to machines. Low artist payment per stream (M). AI DJ feature replaces human radio DJs. Podcast push includes AI-generated content. Daniel Ek's comments about artists needing to produce more frequently reflect optimization-over-craft mindset.",
  "algorithmic_harm_score": 30
},
{
  "name": "Uber",
  "h": 35,
  "u": 22,
  "m": 25,
  "a": 35,
  "n": 28,
  "tags": ["technology", "transportation", "gig economy"],
  "notes": "Surge pricing algorithm exploits high-demand situations. Driver classification as contractors distances company from labor protections. Algorithmic management of drivers \u2014 deactivation without human review, opaque rating systems. Uber Files leak revealed lobbying and regulatory evasion. Uber Eats dark kitchen model reduces restaurant human employment. Upfront pricing algorithm lacks transparency.",
  "algorithmic_harm_score": 40,
  "subsidiaries": ["Uber Eats", "Postmates", "Drizly"]
},
{
  "name": "Airbnb",
  "h": 48,
  "u": 38,
  "m": 35,
  "a": 42,
  "n": 35,
  "tags": ["technology", "hospitality", "marketplace"],
  "notes": "Pricing algorithm can manipulate host expectations. Platform displaces hotel workers (structural). But maintains human-to-human connection model at its core. Anti-discrimination policies improved after documented bias. Community impact concerns in housing markets. Relatively low algorithmic manipulation compared to social media platforms.",
  "algorithmic_harm_score": 20
},
{
  "name": "Snap Inc.",
  "h": 38,
  "u": 28,
  "m": 30,
  "a": 40,
  "n": 25,
  "tags": ["technology", "social media"],
  "notes": "Streaks feature gamifies daily engagement \u2014 designed for addiction, primarily targeting minors. Spotlight algorithm mimics TikTok engagement patterns. My AI chatbot for teens raises safety concerns. Snap Map location sharing has stalking implications. But ephemeral messaging model has some privacy benefits. AR features augment rather than replace human creativity.",
  "algorithmic_harm_score": 45
},
{
  "name": "TikTok / ByteDance",
  "h": 25,
  "u": 18,
  "m": 15,
  "a": 30,
  "n": 12,
  "tags": ["technology", "social media", "entertainment"],
  "notes": "For You Page algorithm is the most potent engagement engine ever built \u2014 optimizes for watch time with no human editorial judgment. Documented negative effects on teen attention spans and mental health. Data governance concerns due to ByteDance/China relationship. Content moderation struggles with scale. Creator economy model pays creators but extracts disproportionate value. Algorithm determines cultural relevance \u2014 unprecedented power for a non-human system.",
  "algorithmic_harm_score": 68,
  "subsidiaries": ["CapCut", "Lemon8"],
  "primary_contractors": ["ByteDance (parent, China-based)"]
},
{
  "name": "Pinterest",
  "h": 42,
  "u": 45,
  "m": 48,
  "a": 38,
  "n": 42,
  "tags": ["technology", "social media"],
  "notes": "Historically lower algorithmic manipulation than other social platforms \u2014 intent-based rather than engagement-based. Body image concerns in early years addressed with policy changes. Shopping integration is transparent. Banned weight loss ads proactively. Workplace culture issues (discrimination lawsuit settled). Algorithm serves search intent rather than manufacturing engagement.",
  "algorithmic_harm_score": 22
},
{
  "name": "Shopify",
  "h": 55,
  "u": 45,
  "m": 48,
  "a": 48,
  "n": 42,
  "tags": ["technology", "e-commerce", "platform"],
  "notes": "Empowers small business owners \u2014 fundamental human-empowerment model. AI tools (Sidekick, Magic) positioned as merchant augmentation. But app ecosystem creates dependency. Laid off 20% of workforce (2023) citing AI as partial reason \u2014 contradicts augmentation messaging. Low direct algorithmic harm \u2014 facilitates commerce rather than manipulating behavior.",
  "algorithmic_harm_score": 8
},
{
  "name": "Stripe",
  "h": 58,
  "u": 48,
  "m": 55,
  "a": 48,
  "n": 48,
  "tags": ["technology", "fintech", "payments"],
  "notes": "Engineering-driven culture. Climate fund investment. Enables businesses of all sizes.",
  "algorithmic_harm_score": 5
},
{
  "name": "Palantir Technologies",
  "h": 55,
  "u": 25,
  "m": 20,
  "a": 38,
  "n": 18,
  "tags": ["technology", "data analytics", "defense"],
  "notes": "Surveillance algorithms used by government agencies and law enforcement. Predictive policing contracts raise civil liberties concerns. ICE contract facilitated immigration enforcement. Military applications (Project Maven successor work). Alex Karp publicly defends government work as ethical obligation. High craft in engineering but applied to monitoring human populations. Low transparency on specific deployments.",
  "algorithmic_harm_score": 55
},
{
  "name": "Zoom",
  "h": 45,
  "u": 42,
  "m": 38,
  "a": 45,
  "n": 32,
  "tags": ["technology", "communications"],
  "notes": "Connects humans but adding AI summaries. Privacy concerns in early pandemic.",
  "algorithmic_harm_score": 5
},
{
  "name": "Dropbox",
  "h": 52,
  "u": 42,
  "m": 45,
  "a": 48,
  "n": 40,
  "tags": ["technology", "cloud storage"],
  "notes": "Shifted to virtual-first. AI features growing. Decent privacy stance.",
  "algorithmic_harm_score": 5
},
{
  "name": "OpenAI",
  "h": 40,
  "u": 30,
  "m": 25,
  "a": 35,
  "n": 20,
  "tags": ["technology", "AI"],
  "notes": "Building the most powerful AI systems in history \u2014 direct displacement potential across knowledge work. Rapid deployment pace concerns safety researchers (multiple departures). Capped-profit structure is novel but governance turbulence (board crisis 2023) raises accountability questions. GPT models increasingly capable of replacing human writers, coders, analysts. Some augmentation positioning (Copilot via Microsoft) but foundational technology enables displacement at scale. Charter claims 'broadly benefit humanity' but commercial incentives accelerating.",
  "algorithmic_harm_score": 28
},
{
  "name": "Anthropic",
  "h": 45,
  "u": 42,
  "m": 48,
  "a": 38,
  "n": 42,
  "tags": ["technology", "AI"],
  "notes": "Constitutional AI approach represents genuine attempt at safety-first development. Responsible scaling policy is industry-leading. But still building systems that displace human knowledge work. B Corp certified (rare for AI company). Higher transparency than competitors on safety research. Slower deployment pace than OpenAI reflects caution. Claude positioned as assistant/augmentation rather than replacement \u2014 but capability growth may outpace positioning.",
  "algorithmic_harm_score": 15
},
{
  "name": "37signals / Basecamp",
  "h": 82,
  "u": 78,
  "m": 75,
  "a": 62,
  "n": 80,
  "tags": ["technology", "software"],
  "notes": "Small team, anti-growth philosophy. No AI in core products. Strong worker benefits.",
  "algorithmic_harm_score": 5
},
{
  "name": "DuckDuckGo",
  "h": 70,
  "u": 72,
  "m": 85,
  "a": 55,
  "n": 90,
  "tags": ["technology", "search", "privacy"],
  "notes": "Privacy-first model. Anti-surveillance. Small human team. Very high transparency.",
  "algorithmic_harm_score": 3
},
{
  "name": "Mozilla",
  "h": 72,
  "u": 68,
  "m": 78,
  "a": 52,
  "n": 85,
  "tags": ["technology", "software", "nonprofit"],
  "notes": "Open source foundation model. Human-rights focused. Some AI adoption with ethical guidelines.",
  "algorithmic_harm_score": 8
},
{
  "name": "Signal Foundation",
  "h": 78,
  "u": 75,
  "m": 92,
  "a": 58,
  "n": 95,
  "tags": ["technology", "communications", "privacy", "nonprofit"],
  "notes": "Nonprofit. End-to-end encryption. Anti-surveillance. No data monetization. Maximum transparency.",
  "algorithmic_harm_score": 2
},
{
  "name": "Proton AG",
  "h": 72,
  "u": 70,
  "m": 88,
  "a": 55,
  "n": 88,
  "tags": ["technology", "privacy", "email"],
  "notes": "Privacy-first email and VPN. Swiss jurisdiction. Open source clients. No advertising model.",
  "algorithmic_harm_score": 2
},
{
  "name": "Automattic / WordPress",
  "h": 68,
  "u": 62,
  "m": 70,
  "a": 55,
  "n": 75,
  "tags": ["technology", "software", "publishing"],
  "notes": "Powers 43% of the web. Open source core. Enables human publishers and creators.",
  "algorithmic_harm_score": 8
},
{
  "name": "Framework Computer",
  "h": 78,
  "u": 72,
  "m": 82,
  "a": 75,
  "n": 85,
  "tags": ["technology", "hardware"],
  "notes": "Modular, repairable laptops. Anti-planned-obsolescence. Right-to-repair champion.",
  "algorithmic_harm_score": 2
},
{
  "name": "Fairphone",
  "h": 80,
  "u": 75,
  "m": 88,
  "a": 82,
  "n": 88,
  "tags": ["technology", "hardware", "mobile"],
  "notes": "Fair trade electronics. Modular repairable phones. Conflict-free minerals. B Corp.",
  "algorithmic_harm_score": 2
},
{
  "name": "System76",
  "h": 75,
  "u": 68,
  "m": 72,
  "a": 55,
  "n": 78,
  "tags": ["technology", "hardware"],
  "notes": "US-manufactured Linux computers. Small dedicated team. Open source firmware.",
  "algorithmic_harm_score": 3
},
{
  "name": "iFixit",
  "h": 82,
  "u": 80,
  "m": 90,
  "a": 78,
  "n": 92,
  "tags": ["technology", "repair", "education"],
  "notes": "Right-to-repair advocacy. Free repair guides. Community-driven. Maximum transparency.",
  "algorithmic_harm_score": 2
},
{
  "name": "Walmart",
  "h": 38,
  "u": 28,
  "m": 32,
  "a": 30,
  "n": 28,
  "tags": ["retail", "grocery"],
  "notes": "Largest private employer in the US \u2014 massive H dimension weight. Increasing self-checkout and automation in stores. Wages historically low but improving. Supply chain labor practices under scrutiny globally. Flipkart/India operations expand reach. Low algorithmic harm \u2014 retail, not platform. But worker surveillance technology increasing.",
  "algorithmic_harm_score": 18,
  "subsidiaries": ["Sam's Club", "Flipkart", "PhonePe"],
  "primary_contractors": ["Supply chain vendors (thousands)"]
},
{
  "name": "Target",
  "h": 42,
  "u": 48,
  "m": 40,
  "a": 42,
  "n": 38,
  "tags": ["retail"],
  "notes": "Shipt acquisition maintains gig worker structure (contractor model). Store experience emphasizes human interaction more than competitors. DEI commitments strong but faced political backlash. Employee wages competitive. Algorithmic pricing and inventory management standard for retail. Circle loyalty program collects data but low manipulation.",
  "algorithmic_harm_score": 12,
  "subsidiaries": ["Shipt"]
},
{
  "name": "Costco",
  "h": 65,
  "u": 70,
  "m": 72,
  "a": 48,
  "n": 55,
  "tags": ["retail", "grocery"],
  "notes": "Industry-leading employee wages and retention. Human-first retail model \u2014 minimal self-checkout, staffed departments, in-house bakery/meat cutting. Low algorithmic manipulation. Kirkland brand maintains quality focus over optimization. CEO pay ratio among lowest in retail. Membership model creates sustainable revenue without ad-driven engagement. Environmental practices improving. One of the strongest H and U scores in retail.",
  "algorithmic_harm_score": 5
},
{
  "name": "Etsy",
  "h": 75,
  "u": 65,
  "m": 60,
  "a": 52,
  "n": 62,
  "tags": ["retail", "marketplace", "handmade"],
  "notes": "Platform for human makers and artisans. B Corp certified. Seller fee controversies.",
  "algorithmic_harm_score": 10
},
{
  "name": "IKEA / Ingka Group",
  "h": 55,
  "u": 58,
  "m": 55,
  "a": 62,
  "n": 52,
  "tags": ["retail", "furniture", "home"],
  "notes": "Mix of automation and human craft. Renewable investment. Circular economy initiatives."
},
{
  "name": "Trader Joe's",
  "h": 72,
  "u": 75,
  "m": 68,
  "a": 52,
  "n": 45,
  "tags": ["retail", "grocery"],
  "notes": "High employee satisfaction. Human-driven store experience. No self-checkout."
},
{
  "name": "Home Depot",
  "h": 48,
  "u": 48,
  "m": 45,
  "a": 40,
  "n": 40,
  "tags": ["retail", "home improvement"],
  "notes": "Human expertise in stores but growing self-checkout and AI."
},
{
  "name": "Lowe's",
  "h": 48,
  "u": 45,
  "m": 42,
  "a": 40,
  "n": 38,
  "tags": ["retail", "home improvement"],
  "notes": "Similar to Home Depot. Growing automation. Community investment programs."
},
{
  "name": "Best Buy",
  "h": 45,
  "u": 42,
  "m": 38,
  "a": 42,
  "n": 35,
  "tags": ["retail", "electronics"],
  "notes": "Geek Squad human service model. Reducing floor staff. E-waste recycling."
},
{
  "name": "REI Co-op",
  "h": 68,
  "u": 75,
  "m": 72,
  "a": 65,
  "n": 62,
  "tags": ["retail", "outdoor"],
  "notes": "Co-op model. Employee profit sharing. Opt Outside campaign. Environmental advocacy."
},
{
  "name": "Nordstrom",
  "h": 58,
  "u": 65,
  "m": 55,
  "a": 45,
  "n": 45,
  "tags": ["retail", "fashion"],
  "notes": "Known for human customer service excellence. Fashion industry supply chain concerns."
},
{
  "name": "Temu",
  "h": 15,
  "u": 8,
  "m": 5,
  "a": 12,
  "n": 3,
  "tags": ["retail", "marketplace"],
  "notes": "Extreme low-cost model. Supply chain opacity. Gamification addiction. Near-zero transparency."
},
{
  "name": "Shein",
  "h": 15,
  "u": 5,
  "m": 5,
  "a": 8,
  "n": 3,
  "tags": ["retail", "fashion", "fast fashion"],
  "notes": "Ultra-fast fashion. AI-driven design. Worker exploitation allegations. Massive environmental footprint."
},
{
  "name": "Wish / ContextLogic",
  "h": 18,
  "u": 15,
  "m": 10,
  "a": 15,
  "n": 8,
  "tags": ["retail", "marketplace"],
  "notes": "Low-cost marketplace. Product quality and safety concerns. Limited transparency.",
  "algorithmic_harm_score": 35
},
{
  "name": "Alibaba Group",
  "h": 28,
  "u": 18,
  "m": 15,
  "a": 25,
  "n": 12,
  "tags": ["retail", "technology", "marketplace"],
  "notes": "Massive marketplace with automation. Limited global transparency.",
  "algorithmic_harm_score": 45
},
{
  "name": "Starbucks",
  "h": 55,
  "u": 48,
  "m": 42,
  "a": 45,
  "n": 45,
  "tags": ["food", "beverage", "retail"],
  "notes": "Barista craft is genuine human skill. Mobile ordering reduces human interaction. Union-busting allegations severely impact U and M. Howard Schultz era emphasized human-centric culture \u2014 post-Schultz direction uncertain. Environmental commitments (reusable cups) improving A. Store algorithm optimizes labor scheduling \u2014 can feel dehumanizing to workers. Benefits historically strong (healthcare, tuition) but union tensions undermine narrative.",
  "algorithmic_harm_score": 10
},
{
  "name": "Ben & Jerry's",
  "h": 78,
  "u": 75,
  "m": 80,
  "a": 65,
  "n": 78,
  "tags": ["food", "ice cream"],
  "notes": "Strong social mission. Fair trade ingredients. Living wage commitment. Social activism."
},
{
  "name": "Nestl\u00e9",
  "h": 38,
  "u": 30,
  "m": 22,
  "a": 32,
  "n": 28,
  "tags": ["food", "beverage", "consumer goods"],
  "notes": "Water privatization. Child labor allegations. Baby formula marketing ethics."
},
{
  "name": "Coca-Cola",
  "h": 42,
  "u": 38,
  "m": 32,
  "a": 28,
  "n": 35,
  "tags": ["food", "beverage"],
  "notes": "Beverage manufacturing maintains human involvement. Marketing historically human-creative but increasing AI-generated campaigns. Environmental concerns from plastic waste (A). Water usage in drought-prone regions. Community investment programs strong. Low algorithmic harm \u2014 product company, not platform. Bottling partner model distances corporate from worker conditions. Strong brand storytelling tradition.",
  "algorithmic_harm_score": 8
},
{
  "name": "PepsiCo",
  "h": 45,
  "u": 38,
  "m": 32,
  "a": 38,
  "n": 35,
  "tags": ["food", "beverage", "snacks"],
  "notes": "Diversified food/beverage portfolio maintains manufacturing jobs. Frito-Lay factory conditions under scrutiny. Environmental commitments improving \u2014 water stewardship. Marketing increasingly AI-assisted but maintains human creative teams. Low algorithmic harm. CEO pay ratio moderate for industry. Community investment programs active.",
  "algorithmic_harm_score": 8,
  "subsidiaries": ["Frito-Lay", "Quaker Oats", "Gatorade"]
},
{
  "name": "McDonald's",
  "h": 38,
  "u": 28,
  "m": 25,
  "a": 28,
  "n": 22,
  "tags": ["food", "restaurant", "fast food"],
  "notes": "Franchise model distances corporate from worker conditions. Dynamic Yield acquisition brought AI-driven menu personalization. Drive-through AI ordering being tested \u2014 direct human displacement. Low craft (H) in food preparation. Worker wages and conditions vary dramatically by franchise. Strong brand but fundamentally optimizing humans out of the operation.",
  "algorithmic_harm_score": 22,
  "subsidiaries": ["Dynamic Yield (AI personalization)"],
  "primary_contractors": ["Franchise operators (95% of locations)"]
},
{
  "name": "Chipotle",
  "h": 58,
  "u": 52,
  "m": 42,
  "a": 48,
  "n": 45,
  "tags": ["food", "restaurant"],
  "notes": "Food with integrity mission. Human kitchen prep. Better sourcing than fast food peers."
},
{
  "name": "Sweetgreen",
  "h": 48,
  "u": 45,
  "m": 55,
  "a": 55,
  "n": 52,
  "tags": ["food", "restaurant"],
  "notes": "Infinite Kitchen automation reduces human roles. Local sourcing. Sustainability focus."
},
{
  "name": "Chick-fil-A",
  "h": 58,
  "u": 65,
  "m": 45,
  "a": 38,
  "n": 35,
  "tags": ["food", "restaurant", "fast food"],
  "notes": "Strong human customer service culture. Political donation controversies."
},
{
  "name": "Whole Foods Market",
  "h": 55,
  "u": 55,
  "m": 48,
  "a": 55,
  "n": 45,
  "tags": ["food", "grocery", "organic"],
  "notes": "Amazon-owned. Previously higher consciousness. Organic focus. Some automation creep."
},
{
  "name": "Clif Bar & Company",
  "h": 68,
  "u": 62,
  "m": 70,
  "a": 72,
  "n": 58,
  "tags": ["food", "snacks", "organic"],
  "notes": "B Corp heritage. Organic ingredients. Community investment."
},
{
  "name": "Newman's Own",
  "h": 75,
  "u": 72,
  "m": 88,
  "a": 62,
  "n": 75,
  "tags": ["food", "grocery"],
  "notes": "100% profits to charity. Organic options. Transparent mission."
},
{
  "name": "Dr. Bronner's",
  "h": 88,
  "u": 85,
  "m": 92,
  "a": 82,
  "n": 90,
  "tags": ["personal care", "organic"],
  "notes": "Family-owned. CEO salary capped at 5x lowest worker. Fair trade. Regenerative farming."
},
{
  "name": "King Arthur Baking",
  "h": 85,
  "u": 82,
  "m": 85,
  "a": 70,
  "n": 80,
  "tags": ["food", "baking"],
  "notes": "Employee-owned (ESOP). B Corp. Community baking education. Transparent sourcing."
},
{
  "name": "Equal Exchange",
  "h": 88,
  "u": 85,
  "m": 90,
  "a": 72,
  "n": 88,
  "tags": ["food", "coffee", "cooperative"],
  "notes": "Worker-owned cooperative. Fair trade pioneer. Direct farmer relationships."
},
{
  "name": "Danone",
  "h": 48,
  "u": 42,
  "m": 52,
  "a": 55,
  "n": 42,
  "tags": ["food", "dairy", "beverage"],
  "notes": "B Corp certified (North America). One Planet One Health mission."
},
{
  "name": "Patagonia",
  "h": 85,
  "u": 82,
  "m": 88,
  "a": 92,
  "n": 85,
  "tags": ["retail", "outdoor", "apparel"],
  "notes": "Gold standard for ethical business. Transferred ownership to environmental trust. Fair Trade certified factories. Repair program extends product life (right-to-repair leader). Transparent supply chain. High craft in product design. Employee benefits exceptional. Low automation, high human involvement at every level. Environmental mission is core, not marketing. Minimal algorithmic anything \u2014 catalogs and stores, not feeds and algorithms.",
  "algorithmic_harm_score": 3
},
{
  "name": "Eileen Fisher",
  "h": 80,
  "u": 72,
  "m": 78,
  "a": 78,
  "n": 68,
  "tags": ["apparel", "fashion"],
  "notes": "B Corp. Circular design. Living wages. Take-back program."
},
{
  "name": "Allbirds",
  "h": 65,
  "u": 60,
  "m": 68,
  "a": 72,
  "n": 70,
  "tags": ["apparel", "footwear"],
  "notes": "Sustainable materials. Carbon footprint labeling. B Corp."
},
{
  "name": "Nike",
  "h": 48,
  "u": 35,
  "m": 32,
  "a": 38,
  "n": 40,
  "tags": ["apparel", "footwear", "sports"],
  "notes": "Supply chain labor practices historically problematic but improved with transparency initiatives. High craft in design (H). SNKRS app uses scarcity algorithms but low overall harm. Strong athlete partnerships maintain human storytelling. DTC shift reduces retail worker jobs. Sustainability initiatives improving but still significant manufacturing footprint.",
  "algorithmic_harm_score": 12
},
{
  "name": "H&M",
  "h": 28,
  "u": 30,
  "m": 25,
  "a": 30,
  "n": 22,
  "tags": ["apparel", "fast fashion"],
  "notes": "Fast fashion model. Supply chain labor issues. Some transparency efforts."
},
{
  "name": "Zara / Inditex",
  "h": 30,
  "u": 25,
  "m": 22,
  "a": 28,
  "n": 32,
  "tags": ["apparel", "fast fashion"],
  "notes": "Fast fashion at scale. Some sustainability commitments. Supply chain complexity."
},
{
  "name": "Everlane",
  "h": 55,
  "u": 48,
  "m": 52,
  "a": 55,
  "n": 62,
  "tags": ["apparel", "fashion"],
  "notes": "Radical transparency on pricing and factories. Some ethical sourcing gaps exposed."
},
{
  "name": "Dansko",
  "h": 78,
  "u": 72,
  "m": 75,
  "a": 65,
  "n": 70,
  "tags": ["footwear", "apparel"],
  "notes": "B Corp. Employee wellness programs. Durable product design."
},
{
  "name": "Tentree",
  "h": 62,
  "u": 60,
  "m": 72,
  "a": 80,
  "n": 72,
  "tags": ["apparel", "sustainable"],
  "notes": "Plants 10 trees per item. B Corp. Transparent supply chain mapping."
},
{
  "name": "Levi Strauss & Co.",
  "h": 58,
  "u": 48,
  "m": 45,
  "a": 42,
  "n": 52,
  "tags": ["apparel", "denim"],
  "notes": "Heritage craft brand. Worker Well-being initiative. Water conservation."
},
{
  "name": "Gap Inc.",
  "h": 35,
  "u": 32,
  "m": 30,
  "a": 35,
  "n": 42,
  "tags": ["apparel", "retail"],
  "notes": "Large-scale manufacturing. Athleta is B Corp. Mixed labor record."
},
{
  "name": "Lululemon",
  "h": 52,
  "u": 45,
  "m": 42,
  "a": 42,
  "n": 38,
  "tags": ["apparel", "athletic"],
  "notes": "Human store experience. Some supply chain concerns. Community yoga programs."
},
{
  "name": "JPMorgan Chase",
  "h": 40,
  "u": 35,
  "m": 30,
  "a": 42,
  "n": 35,
  "tags": ["finance", "banking"],
  "notes": "AI trading algorithms raise market manipulation concerns. Chase app increasingly automated \u2014 human banker access declining. Strong institutional advisory maintains human judgment. Massive workforce but AI investment growing faster than headcount. CEO Jamie Dimon publicly vocal about AI transforming banking \u2014 unclear if augmentation or replacement focus. Regulatory compliance strong but fines history (M).",
  "algorithmic_harm_score": 25,
  "subsidiaries": ["Chase", "J.P. Morgan Asset Management", "J.P. Morgan Wealth Management"]
},
{
  "name": "Bank of America",
  "h": 38,
  "u": 35,
  "m": 32,
  "a": 42,
  "n": 35,
  "tags": ["finance", "banking"],
  "notes": "Erica AI chatbot. Overdraft fee reforms. Climate finance commitments."
},
{
  "name": "Wells Fargo",
  "h": 38,
  "u": 28,
  "m": 18,
  "a": 38,
  "n": 25,
  "tags": ["finance", "banking"],
  "notes": "Fake accounts scandal. Repeated regulatory violations."
},
{
  "name": "Goldman Sachs",
  "h": 45,
  "u": 30,
  "m": 25,
  "a": 40,
  "n": 30,
  "tags": ["finance", "investment banking"],
  "notes": "Algorithmic trading pioneer \u2014 AI displacing human traders for decades. Marcus consumer banking experiment largely failed (human touch missing). Asset management maintains high human judgment. CEO pay among highest in finance. Strong talent pipeline but increasingly technical/AI focused. IPO advisory and M&A work is deeply human (high H in investment banking). Platform Solutions losses reflect difficulty of automated consumer finance.",
  "algorithmic_harm_score": 20,
  "subsidiaries": ["Marcus by Goldman Sachs", "Goldman Sachs Asset Management"]
},
{
  "name": "Vanguard",
  "h": 55,
  "u": 60,
  "m": 65,
  "a": 45,
  "n": 58,
  "tags": ["finance", "investment"],
  "notes": "Investor-owned structure. Human advisors. Low-cost mission."
},
{
  "name": "Fidelity Investments",
  "h": 55,
  "u": 52,
  "m": 48,
  "a": 48,
  "n": 42,
  "tags": ["finance", "investment"],
  "notes": "Family-owned. Human advisor access. Growing AI tools."
},
{
  "name": "PayPal",
  "h": 38,
  "u": 32,
  "m": 38,
  "a": 45,
  "n": 35,
  "tags": ["finance", "fintech", "payments"],
  "notes": "Account freezing controversies. Mass layoffs."
},
{
  "name": "Aspiration",
  "h": 58,
  "u": 60,
  "m": 65,
  "a": 72,
  "n": 62,
  "tags": ["finance", "banking", "sustainable"],
  "notes": "Fossil-fuel-free deposits. Pay-what-is-fair model. Climate-focused banking."
},
{
  "name": "Amalgamated Bank",
  "h": 68,
  "u": 65,
  "m": 75,
  "a": 62,
  "n": 70,
  "tags": ["finance", "banking", "union"],
  "notes": "Union-owned. B Corp. Divested from fossil fuels. Social justice mission."
},
{
  "name": "Johnson & Johnson",
  "h": 48,
  "u": 42,
  "m": 28,
  "a": 38,
  "n": 30,
  "tags": ["healthcare", "pharmaceutical"],
  "notes": "Healthcare fundamentally human \u2014 high structural moat against AI displacement. Talc litigation severely impacts M. Strong R&D investment maintains human scientific craft. Medical device manufacturing requires human precision. Pharmaceutical research maintains human judgment in clinical decisions. Kenvue consumer health spin-off separates lower-moat operations. Environmental compliance improving.",
  "algorithmic_harm_score": 8,
  "subsidiaries": ["Janssen Pharmaceuticals", "DePuy Synthes", "Ethicon"]
},
{
  "name": "Pfizer",
  "h": 52,
  "u": 45,
  "m": 38,
  "a": 35,
  "n": 35,
  "tags": ["healthcare", "pharmaceutical"],
  "notes": "COVID vaccine development showcased human scientific achievement. AI used in drug discovery augments rather than replaces researchers. High craft in pharmaceutical science. Pricing practices (M) controversial \u2014 insulin, oncology drugs. Patent strategies extend monopolies. Strong regulatory compliance. Environmental footprint from manufacturing.",
  "algorithmic_harm_score": 8
},
{
  "name": "CVS Health",
  "h": 48,
  "u": 45,
  "m": 42,
  "a": 38,
  "n": 40,
  "tags": ["healthcare", "pharmacy", "retail"],
  "notes": "Pharmacy human interaction. MinuteClinic human care. Growing self-service."
},
{
  "name": "UnitedHealth Group",
  "h": 35,
  "u": 28,
  "m": 20,
  "a": 38,
  "n": 22,
  "tags": ["healthcare", "insurance"],
  "notes": "Optum's nH Predict algorithm denied elderly patients care \u2014 documented by investigative journalism. Claims denial algorithms prioritize cost over patient outcomes. Change Healthcare acquisition creates data monopoly in health payments. Massive workforce but automating claims processing. CEO compensation among highest in any industry. Strong revenue growth but at what human cost. Healthcare should be the most human industry \u2014 UHG is automating it.",
  "algorithmic_harm_score": 42,
  "subsidiaries": ["Optum", "UnitedHealthcare", "Change Healthcare"]
},
{
  "name": "Seventh Generation",
  "h": 68,
  "u": 65,
  "m": 78,
  "a": 80,
  "n": 75,
  "tags": ["household", "cleaning", "sustainable"],
  "notes": "B Corp. Plant-based formulas. Transparent ingredients."
},
{
  "name": "Burt's Bees",
  "h": 62,
  "u": 58,
  "m": 65,
  "a": 68,
  "n": 60,
  "tags": ["personal care", "natural"],
  "notes": "Natural ingredients focus. B Corp."
},
{
  "name": "Toyota",
  "h": 58,
  "u": 48,
  "m": 42,
  "a": 42,
  "n": 40,
  "tags": ["automotive"],
  "notes": "Kaizen philosophy values human workers. Hybrid leadership."
},
{
  "name": "Ford Motor Company",
  "h": 48,
  "u": 42,
  "m": 42,
  "a": 38,
  "n": 40,
  "tags": ["automotive"],
  "notes": "EV transition. UAW labor relationship. Community investment heritage."
},
{
  "name": "General Motors",
  "h": 42,
  "u": 38,
  "m": 38,
  "a": 48,
  "n": 38,
  "tags": ["automotive"],
  "notes": "Cruise autonomous vehicle setbacks. EV investment. Growing automation."
},
{
  "name": "Rivian",
  "h": 55,
  "u": 52,
  "m": 58,
  "a": 65,
  "n": 55,
  "tags": ["automotive", "electric"],
  "notes": "EV-only manufacturer. Conservation focus. Growing workforce."
},
{
  "name": "Subaru",
  "h": 55,
  "u": 55,
  "m": 58,
  "a": 48,
  "n": 45,
  "tags": ["automotive"],
  "notes": "Zero-landfill manufacturing. Strong owner community. Love Promise."
},
{
  "name": "ExxonMobil",
  "h": 45,
  "u": 30,
  "m": 12,
  "a": 10,
  "n": 15,
  "tags": ["energy", "oil", "gas"],
  "notes": "Climate denial funding history. Major environmental footprint."
},
{
  "name": "Shell plc",
  "h": 45,
  "u": 32,
  "m": 18,
  "a": 15,
  "n": 22,
  "tags": ["energy", "oil", "gas"],
  "notes": "Nigerian delta controversies. Climate pledges but continued fossil expansion."
},
{
  "name": "BP",
  "h": 42,
  "u": 30,
  "m": 15,
  "a": 12,
  "n": 20,
  "tags": ["energy", "oil", "gas"],
  "notes": "Deepwater Horizon legacy. Rolled back climate targets."
},
{
  "name": "NextEra Energy",
  "h": 52,
  "u": 48,
  "m": 55,
  "a": 72,
  "n": 55,
  "tags": ["energy", "renewable", "utility"],
  "notes": "World's largest generator of wind and solar. Some lobbying concerns."
},
{
  "name": "Enphase Energy",
  "h": 58,
  "u": 52,
  "m": 60,
  "a": 82,
  "n": 60,
  "tags": ["energy", "solar", "technology"],
  "notes": "Solar microinverter technology. Enabling distributed clean energy.",
  "algorithmic_harm_score": 3
},
{
  "name": "The Walt Disney Company",
  "h": 52,
  "u": 45,
  "m": 40,
  "a": 38,
  "n": 35,
  "tags": ["entertainment", "media", "streaming"],
  "notes": "Theme parks are deeply human experiences \u2014 high craft, high empathy. Animation maintains human artistic tradition (Pixar, WDAS). But Disney+ algorithm follows Netflix model for content optimization. ESPN increasingly algorithmic. Massive layoffs (7,000+) while investing in streaming technology. Strong creative legacy but commercial pressure increasingly AI-driven. Worker conditions at parks improving but historically problematic.",
  "algorithmic_harm_score": 18,
  "subsidiaries": ["Pixar", "Marvel", "Lucasfilm", "ESPN", "Hulu", "20th Century Studios", "National Geographic"]
},
{
  "name": "The New York Times",
  "h": 72,
  "u": 58,
  "m": 62,
  "a": 45,
  "n": 70,
  "tags": ["media", "journalism"],
  "notes": "Human journalism is core product. Strong editorial standards. OpenAI lawsuit."
},
{
  "name": "The Guardian",
  "h": 75,
  "u": 65,
  "m": 72,
  "a": 48,
  "n": 82,
  "tags": ["media", "journalism", "nonprofit"],
  "notes": "Scott Trust ownership. No paywall. Climate journalism leadership. High transparency."
},
{
  "name": "Substack",
  "h": 68,
  "u": 58,
  "m": 52,
  "a": 48,
  "n": 55,
  "tags": ["media", "publishing", "platform"],
  "notes": "Empowers independent human writers. Creator-first economics.",
  "algorithmic_harm_score": 10
},
{
  "name": "McKinsey & Company",
  "h": 55,
  "u": 35,
  "m": 22,
  "a": 42,
  "n": 20,
  "tags": ["consulting", "professional services"],
  "notes": "Elite human talent. Opioid advisory scandal. Low transparency."
},
{
  "name": "Deloitte",
  "h": 52,
  "u": 42,
  "m": 38,
  "a": 48,
  "n": 42,
  "tags": ["consulting", "audit"],
  "notes": "Large human workforce. Growing AI integration. Audit quality concerns."
},
{
  "name": "Accenture",
  "h": 48,
  "u": 35,
  "m": 38,
  "a": 45,
  "n": 38,
  "tags": ["consulting", "technology"],
  "notes": "Content moderation contractor for major tech \u2014 workers exposed to traumatic content with documented mental health impacts. Simultaneously selling AI replacement solutions to clients while maintaining large human workforce. Consulting model is inherently human but increasingly AI-augmented. Strong DEI initiatives. Global workforce provides employment across developing markets. The tension: Accenture profits from both employing humans AND helping clients replace them.",
  "algorithmic_harm_score": 15,
  "subsidiaries": ["Avanade (joint venture with Microsoft)"],
  "primary_contractors": ["Content moderation workers for Meta, Google, TikTok"]
},
{
  "name": "AT&T",
  "h": 38,
  "u": 30,
  "m": 32,
  "a": 38,
  "n": 28,
  "tags": ["telecommunications"],
  "notes": "Large workforce but steady automation of customer service. Closing retail stores displaces workers. 5G infrastructure investment maintains technical human roles. Union workforce provides some protection. Customer satisfaction historically low \u2014 automated support systems frustrate consumers. Data throttling and pricing practices (M). Rural broadband investment positive.",
  "algorithmic_harm_score": 15,
  "subsidiaries": ["Cricket Wireless", "WarnerMedia (divested to WBD)", "DirecTV (partial)"]
},
{
  "name": "Verizon",
  "h": 40,
  "u": 35,
  "m": 35,
  "a": 40,
  "n": 32,
  "tags": ["telecommunications"],
  "notes": "Similar to AT&T \u2014 large workforce, steady automation. Customer service increasingly chatbot-driven. Network investment maintains engineering roles. Fios fiber provides genuine infrastructure value. Historical media acquisitions (Yahoo, AOL) were mismanaged. Customer data practices improved post-supercookie scandal.",
  "algorithmic_harm_score": 12,
  "subsidiaries": ["Tracfone", "Visible", "Yahoo/AOL (Verizon Media, divested)"]
},
{
  "name": "T-Mobile",
  "h": 42,
  "u": 45,
  "m": 38,
  "a": 38,
  "n": 35,
  "tags": ["telecommunications"],
  "notes": "Better customer service than peers. Human retail experience."
},
{
  "name": "UPS",
  "h": 52,
  "u": 45,
  "m": 48,
  "a": 35,
  "n": 42,
  "tags": ["logistics", "shipping"],
  "notes": "Large human driver workforce. Teamsters union. Some automation in sorting."
},
{
  "name": "FedEx",
  "h": 48,
  "u": 42,
  "m": 42,
  "a": 32,
  "n": 38,
  "tags": ["logistics", "shipping"],
  "notes": "Large workforce. Contractor model for ground raises labor questions."
},
{
  "name": "Southwest Airlines",
  "h": 58,
  "u": 62,
  "m": 55,
  "a": 38,
  "n": 48,
  "tags": ["transportation", "airline"],
  "notes": "Employee-first culture. Profit sharing."
},
{
  "name": "Delta Air Lines",
  "h": 52,
  "u": 55,
  "m": 48,
  "a": 35,
  "n": 42,
  "tags": ["transportation", "airline"],
  "notes": "Profit sharing with employees. Premium service investment."
},
{
  "name": "Marriott International",
  "h": 52,
  "u": 45,
  "m": 42,
  "a": 38,
  "n": 38,
  "tags": ["hospitality", "hotel"],
  "notes": "Large human workforce. Service culture. Data breach history."
},
{
  "name": "Hilton",
  "h": 48,
  "u": 48,
  "m": 45,
  "a": 40,
  "n": 40,
  "tags": ["hospitality", "hotel"],
  "notes": "Great Place to Work reputation. Human service focus."
},
{
  "name": "Khan Academy",
  "h": 72,
  "u": 78,
  "m": 85,
  "a": 52,
  "n": 80,
  "tags": ["education", "nonprofit", "technology"],
  "notes": "Free education mission. AI tutor supplements human learning. Nonprofit. High transparency.",
  "algorithmic_harm_score": 8
},
{
  "name": "Coursera",
  "h": 58,
  "u": 52,
  "m": 55,
  "a": 48,
  "n": 45,
  "tags": ["education", "technology"],
  "notes": "Connects human instructors with learners. Growing AI features.",
  "algorithmic_harm_score": 12
},
{
  "name": "Duolingo",
  "h": 35,
  "u": 32,
  "m": 38,
  "a": 48,
  "n": 40,
  "tags": ["education", "technology", "language"],
  "notes": "Replaced human translators with AI. Gamification engagement.",
  "algorithmic_harm_score": 22
},
{
  "name": "Chegg",
  "h": 30,
  "u": 28,
  "m": 25,
  "a": 45,
  "n": 30,
  "tags": ["education", "technology"],
  "notes": "AI replacing human tutors. Academic integrity concerns.",
  "algorithmic_harm_score": 10
},
{
  "name": "Clearview AI",
  "h": 20,
  "u": 8,
  "m": 5,
  "a": 42,
  "n": 10,
  "tags": ["technology", "surveillance", "AI"],
  "notes": "Facial recognition surveillance. Scraped billions of photos without consent.",
  "algorithmic_harm_score": 90
},
{
  "name": "NSO Group",
  "h": 30,
  "u": 5,
  "m": 2,
  "a": 42,
  "n": 5,
  "tags": ["technology", "surveillance"],
  "notes": "Pegasus spyware. Used against journalists and activists.",
  "algorithmic_harm_score": 92
},
{
  "name": "Ring (Amazon)",
  "h": 30,
  "u": 25,
  "m": 18,
  "a": 35,
  "n": 20,
  "tags": ["technology", "surveillance", "smart home"],
  "notes": "Police partnership program. Neighborhood surveillance network.",
  "algorithmic_harm_score": 35
},
{
  "name": "Darn Tough Vermont",
  "h": 88,
  "u": 80,
  "m": 82,
  "a": 68,
  "n": 75,
  "tags": ["apparel", "manufacturing"],
  "notes": "US-manufactured socks. Lifetime guarantee. Anti-planned-obsolescence."
},
{
  "name": "Lodge Cast Iron",
  "h": 85,
  "u": 75,
  "m": 80,
  "a": 65,
  "n": 72,
  "tags": ["housewares", "manufacturing"],
  "notes": "US-manufactured since 1896. Employee-owned since 2021. Products last lifetimes."
},
{
  "name": "Vermont Country Store",
  "h": 82,
  "u": 80,
  "m": 78,
  "a": 60,
  "n": 70,
  "tags": ["retail", "general store"],
  "notes": "Family-owned since 1946. Human customer service. Anti-Amazon positioning."
},
{
  "name": "Bob's Red Mill",
  "h": 85,
  "u": 82,
  "m": 85,
  "a": 68,
  "n": 78,
  "tags": ["food", "baking", "organic"],
  "notes": "Employee-owned (ESOP). Founder gave company to workers. Stone-milled grains."
},
{
  "name": "Klean Kanteen",
  "h": 72,
  "u": 68,
  "m": 78,
  "a": 78,
  "n": 75,
  "tags": ["housewares", "sustainable"],
  "notes": "B Corp. Climate Neutral. Family-owned. 1% for the Planet."
},
{
  "name": "New Belgium Brewing",
  "h": 75,
  "u": 70,
  "m": 75,
  "a": 78,
  "n": 72,
  "tags": ["beverage", "beer", "craft"],
  "notes": "B Corp. First wind-powered brewery. Community cycling advocacy."
},
{
  "name": "Osprey Packs",
  "h": 78,
  "u": 65,
  "m": 72,
  "a": 62,
  "n": 55,
  "tags": ["outdoor", "gear"],
  "notes": "All Mighty Guarantee (lifetime repair). Durable design philosophy."
},
{
  "name": "Vita Coco",
  "h": 62,
  "u": 55,
  "m": 58,
  "a": 55,
  "n": 48,
  "tags": ["beverage", "coconut water"],
  "notes": "B Corp. Community development in farming regions."
},
{
  "name": "Valve Corporation",
  "h": 62,
  "u": 48,
  "m": 48,
  "a": 42,
  "n": 35,
  "tags": ["technology", "gaming"],
  "notes": "Flat organization. Human game development. Enables indie developers.",
  "algorithmic_harm_score": 20
},
{
  "name": "Electronic Arts",
  "h": 42,
  "u": 30,
  "m": 25,
  "a": 40,
  "n": 30,
  "tags": ["technology", "gaming"],
  "notes": "Microtransaction controversies. Loot box gambling. Mass layoffs.",
  "algorithmic_harm_score": 28
},
{
  "name": "Activision Blizzard (Microsoft)",
  "h": 40,
  "u": 25,
  "m": 20,
  "a": 40,
  "n": 25,
  "tags": ["technology", "gaming"],
  "notes": "Workplace harassment scandals. Creative talent within.",
  "algorithmic_harm_score": 30
},
{
  "name": "Nintendo",
  "h": 68,
  "u": 60,
  "m": 55,
  "a": 45,
  "n": 40,
  "tags": ["technology", "gaming"],
  "notes": "Strong creative human game design. Family-friendly values.",
  "algorithmic_harm_score": 12
},
{
  "name": "SpaceX",
  "h": 58,
  "u": 30,
  "m": 35,
  "a": 32,
  "n": 22,
  "tags": ["aerospace", "technology"],
  "notes": "Deep engineering craft. Grueling work culture. Worker burnout reports.",
  "algorithmic_harm_score": 5
},
{
  "name": "Lockheed Martin",
  "h": 52,
  "u": 38,
  "m": 25,
  "a": 30,
  "n": 28,
  "tags": ["defense", "aerospace"],
  "notes": "Skilled human engineering. Defense ethics debates."
},
{
  "name": "3M",
  "h": 55,
  "u": 48,
  "m": 28,
  "a": 25,
  "n": 30,
  "tags": ["manufacturing", "industrial"],
  "notes": "Innovation culture. PFAS contamination scandal."
},
{
  "name": "Procter & Gamble",
  "h": 45,
  "u": 38,
  "m": 35,
  "a": 38,
  "n": 32,
  "tags": ["consumer goods"],
  "notes": "Large consumer goods. Moderate automation. Some sustainability targets."
},
{
  "name": "Unilever",
  "h": 42,
  "u": 38,
  "m": 42,
  "a": 52,
  "n": 40,
  "tags": ["consumer goods"],
  "notes": "Sustainable Living Plan. B Corp subsidiaries."
},
{
  "name": "TOMS",
  "h": 60,
  "u": 65,
  "m": 68,
  "a": 52,
  "n": 58,
  "tags": ["apparel", "footwear", "social enterprise"],
  "notes": "Impact fund model. B Corp."
},
{
  "name": "Warby Parker",
  "h": 58,
  "u": 60,
  "m": 62,
  "a": 48,
  "n": 58,
  "tags": ["retail", "eyewear", "social enterprise"],
  "notes": "Buy a Pair Give a Pair. B Corp."
},
{
  "name": "Bombas",
  "h": 62,
  "u": 68,
  "m": 72,
  "a": 52,
  "n": 62,
  "tags": ["apparel", "social enterprise"],
  "notes": "One purchased = one donated. B Corp. Human customer service."
},
{
  "name": "Cotopaxi",
  "h": 65,
  "u": 68,
  "m": 75,
  "a": 70,
  "n": 72,
  "tags": ["outdoor", "gear", "social enterprise"],
  "notes": "B Corp. Gear for Good. Repurposed materials. 1% for the Planet."
},
{
  "name": "Impossible Foods",
  "h": 55,
  "u": 55,
  "m": 58,
  "a": 72,
  "n": 55,
  "tags": ["food", "alternative protein"],
  "notes": "Mission-driven alternative to meat. Significant environmental benefit."
},
{
  "name": "Beyond Meat",
  "h": 52,
  "u": 48,
  "m": 55,
  "a": 70,
  "n": 52,
  "tags": ["food", "alternative protein"],
  "notes": "Plant-based mission. Environmental benefit. Ultra-processed labeling debate."
},
{
  "name": "Cisco Systems",
  "h": 48,
  "u": 42,
  "m": 45,
  "a": 40,
  "n": 42,
  "tags": ["technology", "networking"],
  "notes": "Networking infrastructure. Large human workforce. Growing AI integration. Decent sustainability reporting.",
  "algorithmic_harm_score": 8
},
{
  "name": "HP Inc.",
  "h": 48,
  "u": 38,
  "m": 38,
  "a": 42,
  "n": 35,
  "tags": ["technology", "hardware"],
  "notes": "PC and printer manufacturer. Some sustainability programs. Planned obsolescence in ink cartridges.",
  "algorithmic_harm_score": 5
},
{
  "name": "Dell Technologies",
  "h": 48,
  "u": 38,
  "m": 40,
  "a": 40,
  "n": 32,
  "tags": ["technology", "hardware"],
  "notes": "Direct model. Recycling programs. Growing AI server business. Mixed worker reviews.",
  "algorithmic_harm_score": 5
},
{
  "name": "X / Twitter",
  "h": 25,
  "u": 15,
  "m": 12,
  "a": 30,
  "n": 15,
  "tags": ["technology", "social media"],
  "notes": "Post-acquisition (X/Musk): massive workforce reduction (80%+), trust and safety team gutted, verification system monetized undermining authenticity. Algorithm changes increased engagement-bait visibility. Advertiser exodus reflects brand safety concerns. Pre-acquisition: already had misinformation amplification issues. Blue check monetization is transparency regression.",
  "algorithmic_harm_score": 58
},
{
  "name": "Lyft",
  "h": 35,
  "u": 32,
  "m": 28,
  "a": 38,
  "n": 30,
  "tags": ["technology", "transportation", "gig economy"],
  "notes": "Similar gig model to Uber. Some driver support improvements. Pursuing autonomous.",
  "algorithmic_harm_score": 22
},
{
  "name": "DoorDash",
  "h": 28,
  "u": 22,
  "m": 25,
  "a": 35,
  "n": 25,
  "tags": ["technology", "food delivery", "gig economy"],
  "notes": "Gig delivery model. Driver pay controversies. Restaurant commission debates.",
  "algorithmic_harm_score": 25
},
{
  "name": "Instacart",
  "h": 30,
  "u": 25,
  "m": 28,
  "a": 38,
  "n": 25,
  "tags": ["technology", "grocery", "gig economy"],
  "notes": "Gig shopper model. IPO raised worker pay questions. Growing automation.",
  "algorithmic_harm_score": 22
},
{
  "name": "Robinhood",
  "h": 32,
  "u": 25,
  "m": 18,
  "a": 42,
  "n": 28,
  "tags": ["finance", "fintech"],
  "notes": "Gamification of investing. GameStop controversy. Payment for order flow ethics.",
  "algorithmic_harm_score": 28
},
{
  "name": "Coinbase",
  "h": 40,
  "u": 35,
  "m": 32,
  "a": 38,
  "n": 38,
  "tags": ["finance", "crypto", "technology"],
  "notes": "Crypto exchange. Some transparency on operations. Energy concerns from crypto. Mass layoffs.",
  "algorithmic_harm_score": 18
},
{
  "name": "Block (Square)",
  "h": 45,
  "u": 42,
  "m": 40,
  "a": 35,
  "n": 40,
  "tags": ["finance", "fintech", "payments"],
  "notes": "Empowers small businesses. Cash App financial inclusion. Bitcoin mining energy concerns."
},
{
  "name": "Tyson Foods",
  "h": 35,
  "u": 25,
  "m": 20,
  "a": 20,
  "n": 22,
  "tags": ["food", "meat", "agriculture"],
  "notes": "Worker safety issues. Environmental pollution. Animal welfare concerns. Large human workforce."
},
{
  "name": "Kraft Heinz",
  "h": 42,
  "u": 32,
  "m": 30,
  "a": 35,
  "n": 28,
  "tags": ["food", "consumer goods"],
  "notes": "Large processed food company. Cost-cutting culture. Some sustainability programs."
},
{
  "name": "General Mills",
  "h": 48,
  "u": 42,
  "m": 38,
  "a": 40,
  "n": 35,
  "tags": ["food", "consumer goods"],
  "notes": "Regenerative agriculture investment. Some organic brands. Moderate sustainability."
},
{
  "name": "Kellanova / WK Kellogg",
  "h": 42,
  "u": 35,
  "m": 35,
  "a": 38,
  "n": 32,
  "tags": ["food", "consumer goods"],
  "notes": "Worker strike history. Split into two companies. Some sustainability programs."
},
{
  "name": "Annie's Homegrown",
  "h": 62,
  "u": 58,
  "m": 65,
  "a": 68,
  "n": 60,
  "tags": ["food", "organic"],
  "notes": "Organic focus. General Mills owned. Bunny mascot. Regenerative farming support."
},
{
  "name": "Blue Bottle Coffee",
  "h": 65,
  "u": 62,
  "m": 58,
  "a": 55,
  "n": 55,
  "tags": ["food", "coffee"],
  "notes": "Craft coffee focus. Human baristas. Nestle-owned. Sustainability commitments."
},
{
  "name": "Oatly",
  "h": 55,
  "u": 52,
  "m": 58,
  "a": 68,
  "n": 58,
  "tags": ["food", "beverage", "alternative dairy"],
  "notes": "Plant-based mission. Sustainability marketing. Blackstone investment controversy."
},
{
  "name": "Wayfair",
  "h": 35,
  "u": 25,
  "m": 28,
  "a": 32,
  "n": 22,
  "tags": ["retail", "furniture", "e-commerce"],
  "notes": "Algorithm-driven retail. Mass layoffs. Drop-shipping model reduces human craft connection."
},
{
  "name": "Chewy",
  "h": 55,
  "u": 65,
  "m": 55,
  "a": 42,
  "n": 45,
  "tags": ["retail", "pets", "e-commerce"],
  "notes": "Known for exceptional human customer service. Handwritten cards. Pet sympathy gestures."
},
{
  "name": "Zappos",
  "h": 58,
  "u": 68,
  "m": 55,
  "a": 42,
  "n": 48,
  "tags": ["retail", "footwear", "e-commerce"],
  "notes": "Legendary customer service culture. Amazon-owned. Holacracy experiment."
},
{
  "name": "eBay",
  "h": 48,
  "u": 40,
  "m": 42,
  "a": 40,
  "n": 42,
  "tags": ["retail", "marketplace", "e-commerce"],
  "notes": "Enables individual sellers. Growing automation. Some sustainability programs."
},
{
  "name": "Kaiser Permanente",
  "h": 55,
  "u": 55,
  "m": 52,
  "a": 45,
  "n": 48,
  "tags": ["healthcare", "insurance"],
  "notes": "Integrated care model. Large physician workforce. Mental health access improvements."
},
{
  "name": "Mayo Clinic",
  "h": 78,
  "u": 75,
  "m": 72,
  "a": 48,
  "n": 65,
  "tags": ["healthcare", "nonprofit"],
  "notes": "Patient-first nonprofit model. Leading medical research. Human-centered care. Deep expertise."
},
{
  "name": "One Medical (Amazon)",
  "h": 48,
  "u": 48,
  "m": 40,
  "a": 42,
  "n": 38,
  "tags": ["healthcare", "technology"],
  "notes": "Tech-enabled primary care. Human doctors. Amazon acquisition raises data concerns.",
  "algorithmic_harm_score": 10
},
{
  "name": "YETI",
  "h": 55,
  "u": 48,
  "m": 52,
  "a": 48,
  "n": 45,
  "tags": ["outdoor", "housewares"],
  "notes": "Durable product design. Premium quality focus. Moderate supply chain transparency."
},
{
  "name": "Hydro Flask",
  "h": 58,
  "u": 48,
  "m": 55,
  "a": 52,
  "n": 42,
  "tags": ["housewares", "outdoor"],
  "notes": "Reusable bottle advocate. Parks for All program. Durable design."
},
{
  "name": "Leatherman",
  "h": 78,
  "u": 65,
  "m": 72,
  "a": 55,
  "n": 62,
  "tags": ["tools", "manufacturing"],
  "notes": "US-manufactured multi-tools. 25-year warranty. Skilled craftspeople. Portland heritage."
},
{
  "name": "Filson",
  "h": 80,
  "u": 70,
  "m": 72,
  "a": 58,
  "n": 65,
  "tags": ["apparel", "outdoor", "heritage"],
  "notes": "US-manufactured since 1897. Lifetime guarantee. Heritage craft. Durable goods philosophy."
},
{
  "name": "Red Wing Shoes",
  "h": 82,
  "u": 72,
  "m": 75,
  "a": 55,
  "n": 68,
  "tags": ["footwear", "manufacturing"],
  "notes": "US-manufactured work boots since 1905. Resoling and repair program. Multi-generational craft."
},
{
  "name": "Vitamix",
  "h": 75,
  "u": 68,
  "m": 72,
  "a": 55,
  "n": 62,
  "tags": ["housewares", "manufacturing"],
  "notes": "US-manufactured since 1921. Family-owned. 10-year warranty. Quality over planned obsolescence."
},
{
  "name": "Le Creuset",
  "h": 78,
  "u": 65,
  "m": 68,
  "a": 55,
  "n": 58,
  "tags": ["housewares", "cookware"],
  "notes": "French artisan cookware since 1925. Hand-cast and hand-inspected. Lifetime warranty."
},
{
  "name": "Birkenstock",
  "h": 72,
  "u": 60,
  "m": 62,
  "a": 58,
  "n": 55,
  "tags": ["footwear"],
  "notes": "German-manufactured since 1774. Cork and natural materials. Durable design. Heritage craft."
},
{
  "name": "Grove Collaborative",
  "h": 58,
  "u": 58,
  "m": 65,
  "a": 72,
  "n": 62,
  "tags": ["household", "sustainable", "e-commerce"],
  "notes": "B Corp. Plastic-neutral. Sustainable household products. Tree planting program."
},
{
  "name": "Thrive Market",
  "h": 52,
  "u": 58,
  "m": 60,
  "a": 58,
  "n": 48,
  "tags": ["retail", "grocery", "sustainable"],
  "notes": "B Corp. Membership model. Free memberships for low-income families. Organic and sustainable."
},
{
  "name": "Pact",
  "h": 60,
  "u": 55,
  "m": 68,
  "a": 70,
  "n": 65,
  "tags": ["apparel", "organic", "sustainable"],
  "notes": "Organic cotton. Fair Trade certified. Carbon-neutral shipping. Transparent pricing."
},
{
  "name": "Pela Case",
  "h": 58,
  "u": 55,
  "m": 65,
  "a": 78,
  "n": 62,
  "tags": ["technology", "accessories", "sustainable"],
  "notes": "Compostable phone cases. B Corp. Climate Neutral. Plastic-free mission.",
  "algorithmic_harm_score": 2
},
{
  "name": "Who Gives A Crap",
  "h": 68,
  "u": 72,
  "m": 78,
  "a": 75,
  "n": 75,
  "tags": ["household", "sustainable", "social enterprise"],
  "notes": "B Corp. 50% profits to sanitation charities. Sustainable materials. Transparent impact."
},
{
  "name": "Reuters / Thomson Reuters",
  "h": 68,
  "u": 52,
  "m": 58,
  "a": 42,
  "n": 62,
  "tags": ["media", "journalism", "data"],
  "notes": "Wire service journalism. Human reporters worldwide. Growing AI tools. Trust principles."
},
{
  "name": "ProPublica",
  "h": 82,
  "u": 70,
  "m": 85,
  "a": 52,
  "n": 90,
  "tags": ["media", "journalism", "nonprofit"],
  "notes": "Nonprofit investigative journalism. Public interest mission. High transparency. Donor-funded."
},
{
  "name": "Associated Press",
  "h": 72,
  "u": 55,
  "m": 65,
  "a": 45,
  "n": 68,
  "tags": ["media", "journalism"],
  "notes": "Cooperative news organization. Global human reporting network. Some AI adoption in sports/finance."
},
{
  "name": "Wikimedia Foundation",
  "h": 80,
  "u": 72,
  "m": 85,
  "a": 52,
  "n": 92,
  "tags": ["education", "nonprofit", "technology"],
  "notes": "Volunteer-created knowledge. Nonprofit. No ads. Maximum transparency. Human editors.",
  "algorithmic_harm_score": 3
},
{
  "name": "Internet Archive",
  "h": 78,
  "u": 72,
  "m": 82,
  "a": 48,
  "n": 88,
  "tags": ["technology", "nonprofit", "education"],
  "notes": "Digital library for all. Nonprofit. Wayback Machine. Copyright legal battles. Open access mission.",
  "algorithmic_harm_score": 3
},
{
  "name": "Reformation",
  "h": 55,
  "u": 52,
  "m": 58,
  "a": 72,
  "n": 65,
  "tags": ["apparel", "sustainable", "fashion"],
  "notes": "Sustainable fashion. Carbon-neutral. RefScale environmental tracking."
},
{
  "name": "Wegmans",
  "h": 72,
  "u": 75,
  "m": 70,
  "a": 52,
  "n": 52,
  "tags": ["retail", "grocery"],
  "notes": "Consistently rated best employer. Employee-first culture. Scholarship programs."
},
{
  "name": "Publix",
  "h": 68,
  "u": 70,
  "m": 62,
  "a": 45,
  "n": 48,
  "tags": ["retail", "grocery"],
  "notes": "Employee-owned (ESOP). Strong service culture. Community involvement."
},
{
  "name": "ALDI",
  "h": 48,
  "u": 45,
  "m": 48,
  "a": 42,
  "n": 38,
  "tags": ["retail", "grocery"],
  "notes": "Efficiency model. Above-minimum wages. Growing organic selection."
},
{
  "name": "Biogen",
  "h": 58,
  "u": 48,
  "m": 45,
  "a": 45,
  "n": 42,
  "tags": ["healthcare", "pharmaceutical", "biotech"],
  "notes": "Human-intensive R&D. Alzheimer drug controversies. Carbon neutral since 2014."
},
{
  "name": "Moderna",
  "h": 55,
  "u": 45,
  "m": 42,
  "a": 42,
  "n": 40,
  "tags": ["healthcare", "pharmaceutical", "biotech"],
  "notes": "mRNA platform. COVID vaccine. Growing AI in drug discovery."
},
{
  "name": "Patagonia Provisions",
  "h": 85,
  "u": 80,
  "m": 88,
  "a": 90,
  "n": 85,
  "tags": ["food", "sustainable"],
  "notes": "Patagonia's food arm. Regenerative organic. Supply chain transparency."
}
];

if (typeof module !== "undefined") module.exports = { SEED_COMPANIES };
